### ISSUE TITLE
Enable changing of primary device

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#1025]

**Comment by abramsymons** [comment]
We should get a confirmation from users before setting a device as the primary device with something like the following message:

```
Ensure this device is synced before setting it as the primary device, otherwise, you will miss the not synced information. You can only have a single primary device so do not forget to set the other primary device to secondary.
```

**Comment by abramsymons** [comment]
It can be detected if the client is synced recently and show only a message to ask the user to set the other primary device to secondary.
