### ISSUE TITLE
App closes when any connection is pressed

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#1084]
Version: 4.21.1
Device: ?

I have an account for over 3 months. I have established 28 connections so far.
The application works normally and I can access all the menus except the details of the accounts with which I have a connection.
When I try to access a specific information to a certain account, the application crashes.
Under these conditions, I cannot change the status of a connection or establish recovery connections

https://user-images.githubusercontent.com/109460008/193321141-894cb7d8-e98f-4da7-a818-61f2e2dd12a4.mp4

**Comment by adamstallard** [comment]
Can we repro this?

**Comment by a309393r** [comment]
I am using a Samsung Galaxy S20 FE 5G

**Comment by adamstallard** [comment]
> I am using a Samsung Galaxy S20 FE 5G

There was a release 9 days ago which fixed this for some users. (4.21.2) Did it fix it for you?

**Comment by a309393r** [comment]
No. The same problem.
Now I have V.4.22.2
