### ISSUE TITLE
Remove other signing keys after social recovery

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#1087]
Social recovery is the most authoritative recovery method.  After social recovery, all signing keys, secondary devices, and "client apps" (apps needing signing keys) should be removed.  This requires a user to relink any such devices and apps, but prevents a race with an attacker who has stolen someone's BrightID.  Otherwise, the attacker could block the person from completing social recovery by removing any devices they add (assuming the attack took control of their previous primary device).

**Comment by TripleSpeeder** [comment]
I like this. But would it not be better to implement and enforce this directly in our backend as part of the Social Recovery operation?

**Comment by adamstallard** [comment]
> I like this. But would it not be better to implement and enforce this directly in our backend as part of the Social Recovery operation?

Yes I think this could be done automatically on the backend with no additional input from the user.   Moved here https://github.com/BrightID/BrightID-Node/issues/347
