### ISSUE TITLE
Near instant crash on new install on Pixel 7 (Android 13)

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#1089]
Multiple people have reported crashes on the first screen after upgrading to Pixel 7 (Android 13) and attempting to run BrightID with a fresh install.

At least one of these has been sent to Google, so should be available in the dev console.

**Comment by TripleSpeeder** [comment]
This might be https://github.com/facebook/react-native/issues/32735

**Comment by adamstallard** [comment]
The new version of BrightID from the app store (4.22.1) should fix the crashing issue. You can try it on your Pixel 7.
