### ISSUE TITLE
Rename "Devices" to "Devices and Networks"

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#1094]
@abramsymons has been calling apps that can make connections on your behalf "clients" but this is a confusing, overloaded term.

We do need to authorize such apps though.  Examples are "Aura" and "Explorer".  The next examples will likely be Farcaster and Lenster which are social networks that allow cryptographically signed connection making.  The best way to integrate with them is to allow the signing key used in them to be connected with a BrightID.  BrightID nodes can scan blockchains for connections made through Farcaster and Lenster if they know the public parts of these signing keys.

Since this seems to be the future of "clients,"  a fitting name for this kind of app seems to be "Network".  Explorer, Aura, Farcaster and Lenster all fit this concept.

My proposal then is to change "Devices" to "Devices and Networks" and the wording on top to say "Your BrightID is available on the following devices and networks"

**Comment by TripleSpeeder** [comment]
There was only a small code change required to use correct screen title. For the actual string I updated the source string in weblate, so it will be picked up by translators.
