### ISSUE TITLE
Add Connection Party Link to Home Screen if User does not have Meets verification

### ISSUE THREAD

**Issue by UBIpromoter** [BrightID/BrightID#1114]
To help brand new users we should display a link to the Connection Parties https://meet.brightid.org/#/
on the App's Home Screen. (Similar to the Achievement, but more obviously placed so can't be missed.)

Probably right under the verifications shown under the user's name.

**Comment by bitsikka** [comment]
Also, change the time format in the schedule to am/pm with a pull request like this:

https://github.com/BrightID/BrightID-Meet/pull/2

**Comment by TripleSpeeder** [comment]
Similar to #1079
