### ISSUE TITLE
Rename "Recover" and "Import" buttons

### ISSUE THREAD

**Issue by bitsikka** [BrightID/BrightID#1169]
Information Architecture in HCIs need to be consistent to prevent confusion and deliver better participant experience.

Can we please rename "Recover" and "Import" button shown in the interface below to "Social Recovery" and "Device Recovery" to match with the documentation in the gitbook?

![paste](https://user-images.githubusercontent.com/42058840/235593504-58bd3f01-8ffd-4d86-8a8b-aad68783c07b.png)

![Screenshot 2023-05-02 at 12 10 29 PM](https://user-images.githubusercontent.com/42058840/235594147-6b91c658-4e50-4a2f-8f00-3533edddf682.png)

**Comment by Decision20** [comment]
Nice

**Comment by TripleSpeeder** [comment]
Fixed with 4.29.3 release.
