### ISSUE TITLE
Losing connections and linked apps after account recovery

### ISSUE THREAD

**Issue by mrjavanmardi** [BrightID/BrightID#1195]
I lost all my connections (even the recovery ones) and all my linked apps after I recovered my account by using Recovery connections method.
The App asked me to enter my password, and accept it without any errors.
but when the home page refreshed, it shows that I don't have any Connections and linked apps.
and now when I want to link my account to some apps(which I linked before) it shows me the bottom error.

![photo_2023-11-25_11-10-21](https://github.com/BrightID/BrightID/assets/108928246/dc593cc1-271b-4660-887c-f97d73c3a9fa)

**Comment by abramsymons** [comment]
The backup server was out of storage and we did not know that.
The following issues are created to decrease the chance of happening that and resolve it if it happens.
https://github.com/BrightID/BrightID/issues/1198
https://github.com/BrightID/BrightID-Alert/issues/11
