### ISSUE TITLE
Retry backup photo if it has failed

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#1198]
The client tries to back up the connection photo only once when the user makes the connection.
It's generally useful to retry on the next startup if the backup of some connections has failed.
Resolving this issue is a high priority because the backup service was down from 10 Dec 2023 to 9 Jan 2024 for a month.

**Comment by alimahdiyar** [comment]
Regarding #1195, Even if the backup service works correctly, the linked apps are not restored by recovery, right?

**Comment by alimahdiyar** [comment]
My suggestion is to store the latest successful backed up data after calling the `backupThunk` here:
https://github.com/BrightID/BrightID/blob/e8eaac324cec4e5e11c93a02e36ce6c3ad2aa51a/BrightID/src/components/Onboarding/RecoveryFlow/thunks/backupThunks.ts#L82

And then everytime the HomeScreen opens and fetchUserInfo is called, we check if  the new data is different from the backup data, and submit the data to backup service if the data is different.

This also fixes #1209
