### ISSUE TITLE
UI design for displaying groups

### ISSUE THREAD

**Issue by stellarmagnet** [BrightID/BrightID#12]
List Groups
![groups](https://github.com/BrightID/BrightID/raw/master/images/Groups.png)

View Group
![view-group](https://github.com/BrightID/BrightID/raw/master/images/View%20Group.png)

**Comment by adamstallard** [comment]
![connect](https://github.com/BrightID/BrightID/raw/master/images/Groups.png)

**Comment by adamstallard** [comment]
![view-group](https://github.com/BrightID/BrightID/raw/master/images/View%20Group.png)
