### ISSUE TITLE
UI Design for Group Creation

### ISSUE THREAD

**Issue by stellarmagnet** [BrightID/BrightID#14]

**Comment by adamstallard** [comment]
To create a group you choose two co-founders.  Each group is uniquely identified by its three co-founders, i.e. three co-founders can't create more than one group.

The other parameters you choose are
* connection to % of group members to join.  Someone has to have a connection to this % of members in the group to be automatically invited to join.  Allowed values: 51% to 100%
* connection to % of group members to stay in the group.  This allows members to remove someone by breaking their connections with them.  Allowed values: 25% to 100%

To become a co-founder, you "create" a group with the same settings as the other two co-founders.  As soon as all three co-founders have submitted identical group creation requests (and a group with those three members doesn't already exist), the new group is created.

While a group is still in the "pending" stage--i.e. one or two, but not three co-founders have "created" it, there needs to be an option to cancel or withdraw the creation.

This is probably the trickiest screen as far as UI, so I'm willing to take any suggestions on how to simply it.
