### ISSUE TITLE
I need images from some of the sketches

### ISSUE THREAD

**Issue by RnbWd** [BrightID/BrightID#144]
Guy fox mask
bottom nav icons
green success checkmark
add photo icon

**Comment by stellarmagnet** [comment]
Here you go let me know if this covers it:
https://www.dropbox.com/sh/2lqqyzcb0kgaiuf/AACuNZwV7jFJZOvnPc4z6rVQa?dl=0

**Comment by stellarmagnet** [comment]
I can do a PR if you let me know where the dir is for icons

**Comment by RnbWd** [comment]
can you try sending the green arrow again por favor?

**Comment by RnbWd** [comment]
thanks!!
