### ISSUE TITLE
API calls to add/remove membership to a group

### ISSUE THREAD

**Issue by stellarmagnet** [BrightID/BrightID#16]

**Comment by stellarmagnet** [comment]
"Leaving a Group
You can leave a group at any time from the groups tab. The group will move from the Current section to the Eligible section. The group will no longer influence your trust score.

You may also be removed from a group if you fail to keep up a minimum number connections with members. This can happen as a group grows or if members remove their connections with you."

@adamstallard I think if you leave a group, it shouldn't be eligible again. User needs to be invited back before it's eligible. What do you say? This would make the flow consistent for both use cases of:
* user leaves group
* user is removed from group

**Comment by adamstallard** [comment]
Eligibility is automatic based on how many connections you have to other members of the group.  People aren't invited to groups--they just become "eligible" after making enough connections; then they choose (or don't choose) to join the group.

I imagined this flow of the group you're leaving going back to the "eligible" section as a way for someone to "undo" an accidental self-removal from a group.

Is there a better way?

**Comment by stellarmagnet** [comment]
Ah i am reading the further details and i see that now.

What are these groups? like what are people naming them? After a user joins one group with 30 of their friends, why would they create another group?

**Comment by adamstallard** [comment]
I never clarified that, sorry.  I think we should allow people to nickname groups whatever they want, but that nickname won't be stored on the server--it's local storage, just like the names and pictures of your connections.  What is stored on the server are the ids of the three founders and all the members.  For displaying a group someone hasn't joined (and therefore hasn't nicknamed yet)--I think the names of the first three members that are also in their own connections would work--for example (Spacewoman, Alice, Frank).  Then once they join, they can nickname it "Jones Family" or whatever.

This api call:

https://github.com/BrightID/BrightID/issues/23

Will get you the membership for the groups you belong to or are eligible to join.  By browsing the membership and looking at the group's trust score, you should be able to decide to join.

Most people won't have many groups.  You only need one.  The average would probably be between one and two.  The reason to make a new one would be to include someone who needs a group, knows you well, but doesn't fit in your existing groups.  There may need to be multiple intersecting groups to make sure everyone can get into at least one group.  If you belong to more than a few groups, you're probably working really hard to connect isolated people, which is great.
