### ISSUE TITLE
Remove QR code from screen if it has expired.

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#195]
The profile service has a time limit in which a new QR can be used.  If the QR code exceeds this limit, the user should be navigated to a place where they can create a new one (currently , that would be the home screen).  Trying to scan an old QR code will fail.

**Comment by adamstallard** [comment]
Idea: emit an event to navigate to the home screen after a timeout.

**Comment by adamstallard** [comment]
Could emit `connectFailure` .  See

https://github.com/BrightID/BrightID/blob/df4a4b4c3145cb60f1d29eb75ba15988e2267dae/BrightID/src/components/NewConnectionsScreens/ScanCodeScreen.js#L46

**Comment by RnbWd** [comment]
what should the timeout be?

**Comment by adamstallard** [comment]
I would say let's make the timeout as long as a user would be willing to wait for a connection before wanting to try again.

The thought that came to my mind was "one minute."

Whatever we make this timeout is also how long we should leave the web socket connections open and the TTL for the data on the profile service.  We could set another timeout in the mobile app when users connect to a websocket that will do a websocket .close() after some amount of time so they can try again. We can handle the close() event (whether it's from the server or from our timeout) and have the user start the connection process over if adding the connection wasn't completed.
