### ISSUE TITLE
Require a photo

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#196]
It creates problems (especially trying to read the non-existing photo from the filesystem)  if there is no photo, therefore require a photo in initial registration.

**Comment by RnbWd** [comment]
I'm currently downloading a photo from https://loremflickr.com using rn-fetch-blob, and saving the base64 in the same format as an uploaded picture if the photo is empty (for filesystem stability) - i think i'll move that option inside the photo picker for testing
