### ISSUE TITLE
UI Mockups for docs

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#2]
From Nov 3, 2017 conversation in https://hub.decstack.com/projects/channels/brightside (join: http://tinyurl.com/decstack-projects-invite)

see what you can glean from the readme and take a stab at it.

For the mockups simple is better.  For instance, for the "authorization" screen could literally just be a mobile phone screen showing the message "Do you authorize Greshm  to access your Brightside uniqueness verification status?".  Then the "interaction screen" could show someone's name, picture, date, time, and a simple message like "interacted with Nick N. today" or "Had lunch with Nick N." and then "verify" and "don't verify" button.

**Comment by adamstallard** [comment]
More ideas about what the interaction client will be:

https://github.com/adamstallard/brightside/wiki/Interaction-Client

**Comment by NickXML** [comment]
Ok. Some initial thoughts. Let me know if I'm off base anywhere.

There are two paths (for now) that we are considering:

1. First time through (startup/registration)
2. Day to day use

**First Time Use**

1. App loads (probably want a splash screen here)
2. Short introduction
3. Prompt for user name
4. Verify user name
5. Prompt for avatar
6. Verify avatar
7. Go to Daily Use screen

_Some Questions_

- Do you allow duplicate user names across the system or does every username have to be unique?
- Are there any other restrictions or suggestions for user names?
- Do you allow the user to change their user name while retaining the underlying identity?
- Does the avatar need to be a "live" photo or can it be any image?
- Do you allow the user to change their avatar image?

**Daily Use**
Seems there are really only three things you would want to do. Possibly four (see questions, below).

1. Update/Edit profile (change image or username)
2. Record Interaction
3. Review Contacts

And possibly
4. Authorize external app/service.

_Some Questions_

- Do we need to provide guidelines on how to record the interaction?
- Should the guidelines be dismissible? i.e. "Don't show me this again". 
- What about some kind of dual proof/dual recording i.e. I prove you and you prove me at the same time?
- "Open Brightside and hit record. You'll see the other person's name and image." How does this work in practice? How will the app _know_ the other person's name and image?
- Will you collect additional data from the smartphone when recording an interaction? e.g. GPS, time/date (embedded in the recording anyway) etc...
- Do you want to create fixed categories (tags that can be toggled easily) for interaction e.g. Social, Transaction, Business, Family etc. The downside is that it's restrictive. The upside is you'll get much more coherent data than a free form text box. You could also offer tags + text box.
- Should we gamify interaction recording a little? For example, at least have a counter somewhere on the app home page that says "You've captured 123 interactions". Some simple achievement/badging might work wonders here.
- Does the app need a formal Profile page? It could include some basic stats and links to what you've authorized (with links to revoke) etc.
- Will authorizations be handled as a notification/popup? i.e. I register with app X, it triggers a notification on my phone, I approve the app's access.
- Can I trigger an authorization for an app from the phone? It seems a lot more logical to me to make this one-way from the app I am signing up for, rather than from within the Brightside app. If that's the case, there's no need for an App Authorizations screen. You just need a list of authorized apps and the ability to revoke them.
- If you revoke an app, do we delete it from the list or archive it somewhere?
- Should there be an "About" link that goes to a consumer-facing site? This could be in the profile page.

**Comment by adamstallard** [comment]
>Do you allow duplicate user names across the system or does every username have to be unique?

They don't have to be unique, but if you have more than one person in your contact book, there should be some memorable way to differentiate the names (other than just by the avatar).  By default it could be as simple as numbering Joe(1) and Joe(2).  You should be able to rename your own contacts as you please (and possibly add other visual/verbal clues) to help you distinguish between them.  Your name and avatar are sent to other peoples contacts books to help them remember you.  That's really their sole purpose.  You could show up differently in different people's books and it really doesn't matter.  So the "system" has no knowledge or record of your user name(s) / avatar(s), these are only stored in other people's books.

>Are there any other restrictions or suggestions for user names?

Great question.  I think we can be a lot less restrictive than your typical username, since the username never has to match anything else.  The goal is to have a name/avatar combination that makes it easy for someone else to recognize you.

>Do you allow the user to change their user name while retaining the underlying identity?

Yes, you can change your name or avatar at any time.  If someone receives a different name or avatar from you, they should have the option to update it in their book.

>What about some kind of dual proof/dual recording i.e. I prove you and you prove me at the same time?

The app does some things automatically for you.  I don't know how much of this the user should see--maybe just an indication of general success.  The first user to record the interaction (order doesn't matter) signs it with their private key and then beams it (NFC) to the other user who also signs it and then sends it to a brightside node.  Then they beam a message saying whether the connection to the brightside node was successful.  Notes about the interaction are stored locally to form a local timeline; but this isn't part of the MVP.

>"Open Brightside and hit record. You'll see the other person's name and image." How does this work in practice? How will the app know the other person's name and image?

The app beams your name/image and public key to the other user

>Will you collect additional data from the smartphone when recording an interaction? e.g. GPS, time/date (embedded in the recording anyway) etc...

Timestamp and both public keys.  This data is then signed by both private keys and sent to a brightside node.  GPS or any other data would be stored locally only to create interesting, shareable timelines (not in MVP).  If the MVP is lacking engagement, maybe we can do a simple, local timeline screen to create interest.  Eventually, this will be a fully functional social network based around f2f interactions to compliment the uniqueness verification service.

>Do you want to create fixed categories

Maybe; certainly hints could help.  Some standardization will help with timeline filtering later.  The category/description piece needs to be optional and fun.  The main purpose is to create a motivation for you to use the app.

>Should we gamify interaction recording a little?

Absolutely, yes.  Anything fun that can motivate the user.

>You've captured 123 interactions". Some simple achievement/badging might work wonders here.

Love it.  Again, this is all local storage.

>Does the app need a formal Profile page? It could include some basic stats and links to what you've authorized (with links to revoke) etc.

Not yet that I can tell.    

>Will authorizations be handled as a notification/popup? i.e. I register with app X, it triggers a notification on my phone, I approve the app's access.

That's how I imagined it

>Can I trigger an authorization for an app from the phone? It seems a lot more logical to me to make this one-way from the app I am signing up for, rather than from within the Brightside app. If that's the case, there's no need for an App Authorizations screen. You just need a list of authorized apps and the ability to revoke them

This is also exactly how I imagined it, thanks for clarifying

>If you revoke an app, do we delete it from the list or archive it somewhere?

This needs to be sent to a brightside node so the nodes can also block verification requests.  Maybe rather than "revoke" it could be called "block" because you also want to block the app from popping up more popups asking for authorization.  And you might want to "unblock" later if you made a mistake.  This is not MVP.

>Should there be an "About" link that goes to a consumer-facing site? This could be in the profile page.
There is no consumer-facing site, so it would just be an about blurb rather than a link, kind of like the popup you see in some apps.

>And possibly 4. Authorize external app/service.

This won't be in the MVP, but I'd like to have it in the docs because I want people to feel secure about using Brightside.

**Comment by adamstallard** [comment]
@NickXML @stuk88 I wanted some feedback on how the contact book should appear in the app.  The tradtional one we see on phones (which you had in your mockup @NickXML ) is great for looking up contact info like phone # s and addresses and emails, because it's alphabetized.

But our two uses are
1. showing/remembering valuable interactions
2. reviewing to spot duplicates or people you've lost contact with that you'd like to remove

For the first, maybe something that shows your contacts ordered by the last time you saw them, with a quick note about what the interaction was, and then these are sized (or otherwise coded) by how important that interaction was.

Do either of you want to take a crack at a design mockup of just that screen?

BTW this isn't to say that we shouldn't link back to the phone's main address book, but that's not the info we need to show.

**Comment by adamstallard** [comment]
Also, I think this one screen--if we get it right--could be a great image to put on docs like the readme to give people a feel for what the app is about.  That and the "connect" screen, which @NickXML already made (but I'm not sure if he's happy with it.)

**Comment by NickXML** [comment]
Hmm. There are a few different challenges here.

1. Would you record interactions with the same person multiple times?
2. How do you identify a duplicate if you can choose any nickname (and change your nickname)?
3. What organizational methods make the most sense?
4. What retrieval methods make the most sense?

My thoughts:
#1 – Yes, this could and would happen both with people you know well (additional verification) and people you don't know well (maybe a merchant or service provider).
#2 – Can we do this via NFC? i.e. the phone tells you someone is a duplicate and highlights the previous entry.
#3 – Alphabetical by nickname, alpha by actual name (if known), timeline/by date, geography/by location. These could probably all be tabs/sort options in the main contacts window.
#4 – Really not sure. Keyword search may not be that helpful given that it relies on you remembering the nickname you assigned to someone.

Thoughts?

**Comment by adamstallard** [comment]
Thanks Nick, I always value your feedback.

1.  Yes, definitely, and frequent interactions could be an indication of how important the relationship is.

When I think about this, I think there should be two views (at least).  __The default view__ should be arranged such that the persons you're most likely to contact again should be most prominent.  The goal is to encourage people to keep using the app.  I like the idea--if possible--of showing us why we value that relationship, maybe by highlighting a valuable interaction we had with that person.

These could be cycled so they aren't stale (kind of like how facebook feeds sometimes cycles through old memories) with a weight toward recency and a subjective "importance" score given by the user (or calculated somehow)--Maybe a 50th birthday celebration is more meaningful than a casual lunch.  Maybe painting a school is more meaningful than babysitting.  I was thinking we show one per user at a time in the "contacts"  This just helps us remember why we value that relationship.  In this way our "contact" book is like a micro feed with one entry at a time per user.  It can link to the corresponding entry in a user's real contact book, but it won't try to be its own contact book.  There could also be an individual feed for each person in our book that shows all the interactions we've had, instead of just one "featured" one.

2. Since the phone sends us a name, photo, and unique id (public key) we'll know if it's just someone who has changed their profile, and our app can update that users profile instead of creating a new one.

That said, users should be encouraged to use familiar names and real photos to help others keep out sybils.  Detecting duplicates is based on our own memories and our own human facial recognition skills.  Of course, brightside augments this by analyzing the social graph and suggesting (with a ⚠️ ) who might be a duplicate, or someone harboring duplicates.  That way you'll notice and scrutinize those. 

__The second view__ is a tab that shows ⚠️ contacts and infrequently contacted contacts.  Users are gently reminded that to look at that tab on a regular basis and make deletions.

3. I don't see a use case for scrolling through an ABC list.  Another thought, though: it might help people remember to actually use brightside if brightside knows about an upcoming interaction and can remind people about it--but then it starts to bleed into a calendar app, and I'm not sure if I like that.  That said, maybe an "appointments" tab does make sense if it can hook into your calendar app.  And "ABC order" could just be a link to your real contact book. 

Timeline, yes, that makes sense, since we like to review what we've recently done.  geography, yes, that's smart--I hadn't thought of that.  But, a visual clue that shows "hey, you're in cleveland, maybe you should go see uncle joe and your friend bert"  is a great use-case.  I like that.

4.  Search/lookup might be a feature for a future version.  for now, just exploring to find what you want is fine, I think.  Pulling up brightside has two main use cases 1. registering an interaction  2. exploring contacts in a reflective manner--maybe for inspiration on who to interact with, or exploring (after a gentle reminder) whom to delete.

**Comment by adamstallard** [comment]
Ideally, instead of a bunch of tabs with different views, I like the idea (if we can be smart enough about it) to show one main view that anticipates what you want with recency, geography, and subjective value as inputs.  roughly, it could go 1) geography 2) recency and 3) value in order of importance to ranking.

Then of course there's the second tab for cleaning up your contacts.

**Comment by adamstallard** [comment]
Do you have anything to contribute @rstallar ?

**Comment by adamstallard** [comment]
Closing this issue in favor of https://github.com/BrightID/BrightID/issues/8
