### ISSUE TITLE
Research: can react native support all the native capabilities that we need?

### ISSUE THREAD

**Issue by stellarmagnet** [BrightID/BrightID#20]
Especially for making a connection.

See https://github.com/BrightID/BrightID/issues/17

**Comment by mradul** [comment]
I've seen some open source projects that support NFC for react native. We'll need to dig a little deeper and see which one to use. I'm not sure about Tap.

**Comment by z3bg** [comment]
https://github.com/whitedogg13/react-native-nfc-manager

Just leave this comment I made on BrightID channel. 
I can investigate better on it

**Comment by adamstallard** [comment]
#42 should be the only thing we need to make sure of
