### ISSUE TITLE
Allow cancel of "Confirm Connection" screen.

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#203]
Right now there is only a single "Confirm Connection" button. If the back button is pressed, it goes back to an eternal spinner on the scan code screen.

**Comment by adamstallard** [comment]
In light of the[ incentive token](https://docs.google.com/document/d/1C4Eo0Q8YpFNtTE-OvDECi2gC9plw3nISrRlPDd0e8ig/edit#), 

An option to "not stake" after making a connection will help people escape social pressure to make a connection to someone they don't feel comfortable about. An unstaked connection won't let you join a group.  The "confirm" connection screen could change into "Connected to X" (Show picture, their age in the network and their verification") "Stake future income on this person using the system honestly?"  "yes" "no"

**Comment by RnbWd** [comment]
fixed by @siftal
