### ISSUE TITLE
Way to show a larger image of a connection in the list (20-40 subs)

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#204]
Right now, connections images are only visible in a small circle.

It would nice to be able to see a larger image to help decide if someone needs to be deleted.

**Comment by johnnynanjiang** [comment]
@adamstallard , is there any specific UI design you would like to apply to the connection list?
![IMG_9685](https://user-images.githubusercontent.com/11918567/90841303-ab367700-e39f-11ea-8aa1-3063e3a7a247.PNG)

**Comment by adamstallard** [comment]
> @adamstallard , is there any specific UI design you would like to apply to the connection list?
> ![IMG_9685](https://user-images.githubusercontent.com/11918567/90841303-ab367700-e39f-11ea-8aa1-3063e3a7a247.PNG)

Let's loop in @RnbWd .  David, what do you think should happen if someone taps someone from their connection list?

**Comment by johnnynanjiang** [comment]
Hi @RnbWd could you please advice on this issue as per @TripleSpeeder 's referral? Thanks.

**Comment by adamstallard** [comment]
Maybe there could be a connection details screen instead of just enlarging the image. What do you think @RnbWd ?
