### ISSUE TITLE
Allow Image Change

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#218]
A user should be able to change their image from the home screen.

**Comment by UBIpromoter** [comment]
This should be prioritized!
Some users deeply care about this.

Some because they choose an inappropriate image at first setup. Others because they just like changing pictures and it will make them feel more engaged with the app and interested in making connections to share their new pic.

**Comment by RnbWd** [comment]
@adamstallard - how would we handle this on the backend? Do we have any way to update the photo across multiple devices?

**Comment by adamstallard** [comment]
@rnbwd no, we just update it on their phone and then it gets updated on other people's phones when they connect or reconnect to them.

**Comment by adamstallard** [comment]
@RnbWd was this released?

**Comment by RnbWd** [comment]
done
