### ISSUE TITLE
Layout glitch on groups tab

### ISSUE THREAD

**Issue by titusz** [BrightID/BrightID#223]
![image](https://user-images.githubusercontent.com/278556/50715270-dbbb8700-107c-11e9-9982-c2b6e83c6320.png)

**Comment by adamstallard** [comment]
happens with shorter screens.

**Comment by RnbWd** [comment]
This screen has been difficult to style

**Comment by siftal** [comment]
It's solved (with issue #258)

**Comment by RnbWd** [comment]
these buttons no longer exist on top of current groups. Current groups should now occupy the entire screen if there are no eligible groups
