### ISSUE TITLE
iphone app crashes when any text is entered in scan code box

### ISSUE THREAD

**Issue by UBIpromoter** [BrightID/BrightID#225]
On two different iphone devices 5 and X we have seen this.
If you type anything in the text box above the QR scanning image the app instantly crashes and lands you back on the iphone home screen.

**Comment by adamstallard** [comment]
Should have been fixed by c49a7c5bde3ccf469ce6195108ae65be891ba2ab https://github.com/BrightID/BrightID/pull/300
