### ISSUE TITLE
Name not visible while typing on sign up screen

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#230]
A user's name won't be visible while typing on an android phone with a shorter screen.  This makes it impossible to see what name you've typed in until you hit enter.

**Comment by pythonpete32** [comment]
Seen same issue on [samsung S7](https://media.giphy.com/media/YpTsEKbjYb9Rej8H4F/giphy.gif)

**Comment by adamstallard** [comment]
This is a problem on Android for users with large fonts. Also the create button is barely visible.

**Comment by RnbWd** [comment]
It works on the latest release, but in the future I would like to spread out signup into individual screens for name and profile picture
