### ISSUE TITLE
Link to chat from within app

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#235]
Provide a link that takes people to the brightid discord from within the app

**Comment by adamstallard** [comment]
Maybe a link that says "BrightID Chat 💬" on the home screen.  Our discord server address is https://discord.gg/Cc57Sh

**Comment by RnbWd** [comment]
https://github.com/BrightID/BrightID/commit/e011fbc4679b5e49eed5254ea40102f8d02795d2

**Comment by adamstallard** [comment]
@RnbWd Don't you think this should be displayed prominently, or at least with an icon that makes it easier to discover.  A "?" symbol doesn't make me think I'm going to be able to chat.
