### ISSUE TITLE
Onboarding Text box to enter name is partially hidden

### ISSUE THREAD

**Issue by theobtl** [BrightID/BrightID#237]
During sign-up, the text box to enter a name is partly hidden. See the upper part of the "T" here: https://photos.app.goo.gl/GbBXfJKMUMZ1H9GN8

Device info: OnePlus 5, Android 9

**Comment by theobtl** [comment]
That said, kudos to the team, idea and implementation are super exciting!

**Comment by adamstallard** [comment]
Duplicate of #230

**Comment by adamstallard** [comment]
Might still be a bug  Also not a dupe of #230 , this is about the top of the font being obscured.  Maybe it's too big for the text box somehow.

**Comment by adamstallard** [comment]
Closing in favor of #230
