### ISSUE TITLE
Removing a connection should offer to flag it in all groups

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#238]
Removing a connection should offer to flag it in all groups known to the user.  Likewise, flagging a connection should offer to flag it in all groups.

This will make less steps for the user who has found a fake or duplicate account.

**Comment by abramsymons** [comment]
Based on the approach we implemented flagging, any user can flag another user if they have connection with each other.

Users see flagging options in their connections list beside removing option, so they can choose if they want to remove or flag someone.

User will automatically be deleted from groups that they have 2 flaggers in them.

I think current implementation is resolving this issue. Am I right?
