### ISSUE TITLE
When two users connect, scores displayed and transferred should come from nodes

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#241]
When scores come from the device, they can be faked. The score should come from one or more nodes trusted by the user viewing the score. Viewing another connection's score is important to preventing social engineering attacks. See #240

**Comment by RnbWd** [comment]
Do we have an API call for this one?

**Comment by adamstallard** [comment]
Not yet.  I just added an issue to create that API method https://github.com/BrightID/BrightID-Node/issues/47

**Comment by adamstallard** [comment]
Unblocked.

Here's the API call https://app.swaggerhub.com/apis/brightid/brightid/1.0.0#/default/get_userScore__user

Try it with this user `rcCzKkbC5uBy5N_Srar5ar4ZxsL453j_NloTcbqCc8U`  for example.

It's deployed on test.  Let me know when it's needed and I'll deploy it to production.
