### ISSUE TITLE
Indicate if someone in your connection list isn't connected to you

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#251]
(This also includes group lists.)

We don't want to automatically remove someone from your lists if they break their connection with you (because you may need to flag them in a group), but it should be indicated in the lists that they aren't connected to you.

This backend API fix is needed first
https://github.com/BrightID/BrightID-Node/issues/45

**Comment by abramsymons** [comment]
We have this implemented and we have these data on GET /users/{id} now:
BrightID/BrightID-Node#45
