### ISSUE TITLE
Create Group section on top should scroll away

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#258]
<img src="https://user-images.githubusercontent.com/205792/53665994-c9e00580-3c21-11e9-91b0-fd00e4ddb235.jpg" height="450">

We should fix the way it scrolls. The top section should not remain fixed - the top section should scroll as well. For example, once I scroll down the entire screen should be filled w my groups.

Also those tiles should be a fixed height, as the design won’t scale well if you show the three full names. So it needs some truncation logic if the names go beyond two lines. Then the tile height should support a maximum of two lines.

We can definitely decrease the default font size of the names there

We should center the text too

--Credit to @stellarmagnet

**Comment by RnbWd** [comment]
this is fixed
