### ISSUE TITLE
Refresh Score, etc on home screen

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#262]
If a new user is on the home screen waiting for their score to update because they just joined a group, it's nice if it can refresh.  Maybe a refresh icon next to the score?  Or just an automatic refresh (call to getUserInfo) on a timer--as long as that's not too spammy to the servers. ( Is there a way to only refresh if the phone's screen is on and BrightID is in focus?)

**Comment by siftal** [comment]
It seems as scores are getting deprecated and verification stickers are replacing that, this issue is outdated and should be closed.
We should clarify the required steps for getting verifications to new users in milestone 5, stars, reputation and  SDK. @adamstallard
