### ISSUE TITLE
Let group of people connect with each other simultaneously

### ISSUE THREAD

**Issue by UBIpromoter** [BrightID/BrightID#263]
When a group of people all want to interconnect to each other, it would be great to have a simple and efficient way to do it that did not require each person  scanning everyone else's individual QR code.

This could take a number of potential forms.
Some quick ideas how it might work (but please think about other better ways)

1) We could create a special group-join QR code button. This would bring up a multiple use QR code that everyone else could scan. A bunch of people could all scan it and then the person who created the code would get a series of notifications allowing them to accept each of the new connections.

2) If we felt this was not secure enough, we could consider making the group scans have to happen in both directions. Each person in the group would show their group-join QR code and have it scanned by each member. Connections only are made when both users have scanned each other's codes. It is easy to envision this on a zoom chat. Each person sequentially holds up their group-join QR code while all others scan. Once everyone has scanned, move on to the next person showing their QR code.

3) Another totally separate possibility could be to create a 'gathering point' (for lack of a better name). Someone generates a gathering point QR code. Everyone else scans the code. And then every person indicates the number of people that are at the gathering point together. If all people at the gathering point indicate the same number then all connections get made. (Or confirmations pop up on everyone's phones and both sides need to confirm each of the new connections.)

4) What else? What would be a better way to facilitate a bunch of people connecting to each other all at once?

**Comment by Alireza-Rahmani** [comment]
@adamstallard I think number 3 is a good solution. My suggestion is that in "new connection" panel there should be another tab as"group connection" when you push it, BrightID should generate a QR code that let's say is valid for 5 minutes, then when you are sitting with your friends and introducing BrightID to them you will generate one group connection QR code and anyone who scans your code will be connected to each other, I mean BrightID will make the connections for everyone so there is no need for them to scan individual QR codes one by one to be connected to each other.

**Comment by adamstallard** [comment]
As a first step, we should create Reusable QR codes #419

**Comment by TripleSpeeder** [comment]
This is implemented through PR #462
