### ISSUE TITLE
Learn more button not working (10-40 subs)

### ISSUE THREAD

**Issue by pythonpete32** [BrightID/BrightID#277]
![](https://media.giphy.com/media/dt0OQF9wsuYDHH1tOX/giphy.gif)

**Comment by TripleSpeeder** [comment]
What is the expected behaviour? Should it open the website at a specific link?

**Comment by adamstallard** [comment]
> What is the expected behaviour? Should it open the website at a specific link?

I think that makes sense.  For now, the best destination for the link is[ this section of the whitepaper](https://docs.google.com/document/d/1CEBWv4ImXsZYQ2Qll7BXojeKI9CGtzRXjB9aFIj00c4/edit#heading=h.nr1odgliy5nk).
