### ISSUE TITLE
"Create My BrightID" button is barely visible

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#286]
Android Galaxy S7

On the Onboarding, when typing in the name, the "Create My BrightID" button becomes obscured by the on-screen keyboard and can't be pressed unless the user hits "enter" for the name.

**Comment by adamstallard** [comment]
@RnbWd I know you've fixed styling on small screens.  Could you see if this is fixed?

**Comment by RnbWd** [comment]
Yes, I might have already fixed this. Looking into it now.

**Comment by RnbWd** [comment]
already fixed
