### ISSUE TITLE
Onboard slides don't work on Android

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#287]
Dev version only.  The slides change erratically and the 3rd and 4th slides aren't viewable.

I have been using an old version of onboard.js that only has the "anonymous" slide for android releases because the dev version is so jarring.

**Comment by RnbWd** [comment]
I think this issue is fixed, it works in my emulator, can somebody please confirm?

**Comment by adamstallard** [comment]
> I think this issue is fixed, it works in my emulator, can somebody please confirm?

Fixed in which branch?

**Comment by adamstallard** [comment]
> I think this issue is fixed, it works in my emulator, can somebody please confirm?

I just installed the play store version on a new device, and although there are only 2 screens in the onboard, it seems to work.  Should we close.

Also curious if you changed / fixed anything recently--if that's what you meant by "this issue is fixed."

**Comment by RnbWd** [comment]
on my device and emulator it works identically to iOS

**Comment by adamstallard** [comment]
> on my device and emulator it works identically to iOS

Ok since we just did a release, I assume that means the fix is out and we can close this.
