### ISSUE TITLE
Downloadable APK

### ISSUE THREAD

**Issue by xuhcc** [BrightID/BrightID#301]
Please create a tagged release on GitHub and provide a downloadable APK for Android, to make BrightID installation possible on devices without Google Play.

**Comment by adamstallard** [comment]
I think it's a good idea to tag releases so it's clear which code is in the version that's in testflight and play store.  Like you say, we could attach an apk to the release.

In the meantime, you can always download the same apk that's in the play store directly from [brightid.org/app](https://www.brightid.org/app/).

**Comment by xuhcc** [comment]
Thanks! I didn't know about that page

**Comment by xuhcc** [comment]
@adamstallard Is it located somewhere else now? The link you suggested earlier is dead.

**Comment by adamstallard** [comment]
@xuhcc Yes, that page didn't carry over to our new website.  Here's a direct link to the apk in google drive:  https://drive.google.com/open?id=1EJIFrf8xPNrES6prB4qYaJogtYwEIKCG
