### ISSUE TITLE
Apps can be added multiple times

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#341]
If you re-link to an app (deep link) it will add it again.

If you delete (trash icon) it will remove all duplicates.

**Comment by adamstallard** [comment]
@RnbWd I know you tried to solve this with https://github.com/BrightID/BrightID/commit/c308e011b4fecf29d50b55b8773028e572f07434 but it's still an issue

**Comment by adamstallard** [comment]
You can use [Bright Ethereum](https://ethereum.brightid.org) to test this.

**Comment by RnbWd** [comment]
I'll test this soon, thanks for sharing the link

**Comment by RnbWd** [comment]
this is a weird issue, I was able to duplicate it once, after deleting an app, I'm looking at all the code closely today, I already found a bug in how we handle operations

**Comment by RnbWd** [comment]
I found the error, but I also fixed a few bugs where the no function was called after opening a deep link
