### ISSUE TITLE
On Backup screen, the confirm password field is blocked on small screens

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#344]
On a small screen on Android, the onscreen keyboard covers most of the confirm password field, so you can't see what you're typing.

Additionally the "complete" message covers the button at the bottom (though it can still be pressed).

**Comment by RnbWd** [comment]
really? I'll take a look at this. How small of device?

**Comment by adamstallard** [comment]
> really? I'll take a look at this. How small of device?

Android Galaxy S7

**Comment by RnbWd** [comment]
fixed
