### ISSUE TITLE
Enable users to change their trusted connections (100-200 subs)

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#346]
**_Please see this [comment below](https://github.com/BrightID/BrightID/issues/346#issuecomment-699543622) for the recommended approach which is similar to 1)_**

Also related to https://github.com/BrightID/BrightID/issues/547 , https://github.com/BrightID/BrightID/issues/548 , and https://github.com/BrightID/BrightID/issues/421

Allowing users to update their trusted connections is challenging because if someone's brightid is stolen, stealer can update the trusted connections first and then use help of new trusted connections to update signingKey of brightid and own that.

We can have different approaches to overcome this challenge:
1) Enable users to add only a single new trusted connection per month for example. In this way users that their brightid are stolen have enough time to update their signingKey before that stealer do that.
2) Enable users to update their trusted connections if one of their old trusted connections approved that. In fact user signature plus one of trusted connections signature are two confirmations.

Which approach do you think is better? @adamstallard @RnbWd

**Comment by adamstallard** [comment]
I like option 2.

Now consider if your trusted connection dies or didn't set their own trusted connections and lost their phone.  In either case they would be flagged--in the first case as "deceased" in the second case as "duplicate."

We should alert a user if one of their trusted connections is flagged and recommend replacing that trusted connection immediately.

**Comment by adamstallard** [comment]
Example UI flow that covers what's needed.  @RnbWd and Dama could simply or improve it.

![Untitled Diagram (1)](https://user-images.githubusercontent.com/205792/82229264-12471a00-98df-11ea-93b8-791b41b2c346.jpg)

1. From the home screen, select "Trusted Connections", go to 2.
2. Goes to new "Trusted Connections Screen".  If they select "Change Trusted Connections" go to 3.
3. Existing trusted connections are shown at top and checked.  The other connections are shown unchecked. Should sort from most recent on top, but needs a search component.  After they have checked at least 3, the "OK" button becomes active.  (There should also be an easy way to cancel.)
4. User sees new Trusted Connections and confirms
5. One of the previous Trusted Connections must scan the code to finalize the update.

**Comment by adamstallard** [comment]
What the previous trusted connection is confirming is that it's the real user that's initiating the change, not someone who stole their phone.

@siftal is making a backend api method for this.

**Comment by adamstallard** [comment]
If it's going to be like how @siftal diagrammed it, then the user should know on step 1. that they will need the help of one trusted connection, otherwise going through the steps might be useless, if they're not already talking with them.

**Comment by adamstallard** [comment]
@siftal should know that the backend api method doesn't require confirmation from an existing trusted connection (at least not yet)

**Comment by abramsymons** [comment]
We can have a switch like:
`[ ] Don't allow resetting trusted connections without verification from one of them`
in future when users choose their trusted connections that can be automatically selected (or not) to enable users decide about the amount of security they need.

**Comment by abramsymons** [comment]
> @siftal should know that the backend api method doesn't require confirmation from an existing trusted connection (at least not yet). We are leaving off the last step for now (until BrightID becomes more popular and theft, bribery, and robbery become risks).

Currently backend api don't allow resetting trusted connections at all. As we want to leave of that verification from one of the old trusted connections, I think adding a password/pin on top of BrightID is a must.

**Comment by adamstallard** [comment]
As I've thought about this more,  I think the first option is going to be easier for users: to let them add one trusted connection if they haven't already added one in the past week.  See https://github.com/BrightID/BrightID-Node/issues/129 This would be even better if we don't allow a trusted connection to be used unless it was set at least a week before. See https://github.com/BrightID/BrightID-Node/issues/128

**Comment by adamstallard** [comment]
By the way, a "trusted connection" should be called a "recovery connection" to make it more clear what they do.

**Comment by TripleSpeeder** [comment]
This has been implemented.
