### ISSUE TITLE
Update backup after deleting connection

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#347]
`backupUser` should be called if `backupCompleted` after deleting connection just like what we did here after adding new connection:

https://github.com/BrightID/BrightID/blob/42bccfa6aac6f74ec92c2bb77bf2acfff6b0ce8a/BrightID/src/components/NewConnectionsScreens/actions/addNewConnection.js#L68-L69

**Comment by RnbWd** [comment]
merged into dev

**Comment by RnbWd** [comment]
this might not be working properly, we need to test this
