### ISSUE TITLE
Text invisible while entering name on ios

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#349]
There have been several reports from users in the previous version and now this one (release v2-3) in the signup screen on ios.  When you type your name, it doesn't show anything in the text entry box.  The box is visible, but the text is transparent or white.

![photo_2020-03-11_18-11-36](https://user-images.githubusercontent.com/205792/76546754-474f7000-6449-11ea-921f-c8deed4ee9db.jpg)

**Comment by RnbWd** [comment]
can I get more information about the specific device they were using? I'll test additional emulators later today

**Comment by adamstallard** [comment]
> can I get more information about the specific devices they were using? I'll test additional emulators later today

iPhone 6s, iOS version 13.3

**Comment by RnbWd** [comment]
ahh its invisible in dark mode!!!

**Comment by RnbWd** [comment]
fixed
