### ISSUE TITLE
Implement pull to refresh on groups page (40-80 subs)

### ISSUE THREAD

**Issue by RnbWd** [BrightID/BrightID#357]

**Comment by x5engine** [comment]
try to knock this out pretty quickly :)

**Comment by x5engine** [comment]
Is this already done?

**Comment by adamstallard** [comment]
> Is this already done?

No.  I just assigned you

**Comment by x5engine** [comment]
thanks

**Comment by adamstallard** [comment]
@x5engine you're right. it's done already. closing

**Comment by RnbWd** [comment]
sorry I thought I closed this issue

**Comment by RnbWd** [comment]
we can still need to implement this on the connections page though
