### ISSUE TITLE
Recover a lost or compromised ID

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#36]
If your ID is lost or compromised*, there should be a way to start the process of replacing it.  This involves reconnecting with a set number (3) of previous connections; each indicating that you are the same person as an existing connection.

The connections that can be used for this need to be pre-selected to avoid takeover attacks. A special 
 third-party service for doing this can also be used.

This will recover your group memberships and score, but it won't automatically retrieve all your names and images you have associated with groups and connections.  To do this, refer to https://github.com/BrightID/BrightID/issues/35

*compromised can mean that an attacker has possession of your private key, or that sensitive personal data has been leaked and associated with your ID

**Comment by adamstallard** [comment]
To avoid attacks where a thief takes over the account by reconnecting to new connections made by the thief, we need to look at the timestamp of the connections and only allow connections over a certain age to qualify for reconnection.

**Comment by alfhg** [comment]
There should be a limit on how frequent an account can replace itself.

**Comment by adamstallard** [comment]
https://sketchboard.me/BBE6TFzrAvIc#/
