### ISSUE TITLE
Change the "waiting" label on a connection after 30 seconds to "problem; connect again" (40-80 subs)

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#364]
Users are sitting around waiting for hours on a connection, wondering what they need to do next. If a connection fails, it's very easy just to try again.

**Comment by TripleSpeeder** [comment]
In addition to changing the label I suggest to add a new entry to the flag menu, allowing the user to remove the pending connection from the list. 
Reasoning: If it is not possible to retry the connection (partner gone, no internet, ...) there is no way for the user to get rid of the waiting connection, it will sit in the connection list forever.

**Comment by adamstallard** [comment]
> In addition to changing the label I suggest to add a new entry to the flag menu, allowing the user to remove the pending connection from the list.
> Reasoning: If it is not possible to retry the connection (partner gone, no internet, ...) there is no way for the user to get rid of the waiting connection, it will sit in the connection list forever.

Or maybe a separate control if the user wouldn't think to look in the flag menu.

**Comment by TripleSpeeder** [comment]
> Or maybe a separate control if the user wouldn't think to look in the flag menu.

Yes, that's better. What do you think of this:

 - Remove the "flag" button until the connection is established. It does not make sense to flag a connection that is not yet established.
 - When the connection is in "waiting" state for more than 30 seconds:
    - Change the label to indicate the connection problem 
    - use the empty space from the flag button to show a "X" button
 - Clicking on X shows a confirmation dialog (something like "Do really want to remove this connection? You can reconnect at any time."). When confirmed, delete the connection from redux state.
