### ISSUE TITLE
Sort Groups Tab by most recent by default (10-40 subs)

### ISSUE THREAD

**Issue by alirezapaslar** [BrightID/BrightID#372]
The default sort should be:

Groups I joined (comes from `groups[]` in `GET /users`) sorted by `joined`

**Comment by TripleSpeeder** [comment]
Working on this one :)

**Comment by adamstallard** [comment]
Great @TripleSpeeder ! You may be able to reuse what is being done on the connections screen for sorting.

**Comment by TripleSpeeder** [comment]
@adamstallard  Just to be clear on requirements - If the user has a primary group it should always be the very first entry, right?

**Comment by adamstallard** [comment]
> @adamstallard Just to be clear on requirements - If the user has a primary group it should always be the very first entry, right?

Until we have a way to visually separate primary groups, they should just be mixed in with the rest of the groups, depending on whether they have a `invited` or `joined` attribute.

**Comment by TripleSpeeder** [comment]
@adamstallard Since currently only the joined groups are displayed in the list i suggest to split this issue: 
 - Keep this for just changing the default sort order in the existing groups list. 
 - Create a new issue to add invited groups to the list. This needs some thoughts from UI/Workflow perspective - How to present the invitations in the list and what user interactions should be possible.

**Comment by adamstallard** [comment]
> @adamstallard Since currently only the joined groups are displayed in the list i suggest to split this issue:
> 
> * Keep this for just changing the default sort order in the existing groups list.
> * Create a new issue to add invited groups to the list. This needs some thoughts from UI/Workflow perspective - How to present the invitations in the list and what user interactions should be possible.

I think what happened is "invited groups" got moved to the notifications screen, not the groups screen recently.  Let's make this issue just about existing groups (not invited groups)
