### ISSUE TITLE
Add FAQ to Website

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#41]
Mostly so we can explain to people how we're different from 

1.  uPort, Civic, Sovrin, Microsoft, etc. etc. etc. etc.

2. Blockstack

Basically explain how we're different than everyone on this page:
http://identity.foundation/

**Comment by adamstallard** [comment]
Also add a section about why biometric tests aren't a good solution for verifying uniqueness.

**Comment by haicu** [comment]
I created an extra page like this https://www.brightid.org/biometrics-and-kyc/
But maybe that's not what you intended?
Did you mean a section on the homepage?

Actually, I don't mind doing it, but you can also create pages and/or sections yourself if you want.

**Comment by adamstallard** [comment]
That previos comment was just a "note to self" reminding me what to put in the FAQ :)

**Comment by haicu** [comment]
Ah of course, very well ...
