### ISSUE TITLE
Reusable QR codes

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#419]
Once a QR has been scanned once, allow it to remain active, but start a counter and timer on it.

A QR can be reused 30 times in 15 minutes. Once either of those limits is reached, the QR code is no longer active.

**Comment by adamstallard** [comment]
blocked by #418 (needs push notifications to work)

**Comment by x5engine** [comment]
is this is a UI change need for the QR code?

**Comment by TripleSpeeder** [comment]
This is implemented through PR #462
