### ISSUE TITLE
Home screen remain in waiting state after scanning deep link and returning from apps screen to home screen

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#442]
When we scan the app deep link qr codes with the BrightID scanner (which generally used to create connections) the screen will be switched to `Apps` tab to create the link. But after creating the link when we come back to `Home` screen, the home screen is still in loading mode. We should fix that to return home screen to the right state after the app linking qr code was scanned.

**Comment by TripleSpeeder** [comment]
This has been fixed with the updated UI.
