### ISSUE TITLE
Using back button after confirming connection shows PreviewScreen again

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#445]
Observed behaviour:

1. scan code -> shows preview screen [OK]
2. confirm connection -> shows success screen [OK]
3. click "done" -> shows Connections screen [OK]
4. use back button -> again shows success screen [**WRONG**]
5. use back button -> again shows preview screen, with random image and missing name [**WRONG**]

Expected behaviour:

Using back button at step 4 should go back to home screen.

**Comment by alirezapaslar** [comment]
A screenshot of the preview screen with random image and missing name.
![Screenshot_20200626-224337_BrightID](https://user-images.githubusercontent.com/46079887/85905420-41687980-b803-11ea-9d41-50ee696f26bb.jpg)
