### ISSUE TITLE
Deep links just open home screen when app is not running

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#461]
Originally reported by rperez89 in keybase brightid#general. 
When brightID app is running in background, opening deep links works as expected.
When brightID app is not running, opening deep links starts the app, but just goes to the home screen, not the actual deep link target.
-> Happens both for 'brightid://' and 'https://app.brightid.org' form
-> Happens both on iOS and Android

**Comment by RnbWd** [comment]
this is fixed

**Comment by RnbWd** [comment]
https://github.com/BrightID/BrightID/pull/456/commits/6d8a44068927c1df571f7b221d9bd1e93ac09b9a

**Comment by TripleSpeeder** [comment]
@RnbWd Can we close this now or is there still work to do?

**Comment by RnbWd** [comment]
I found something in the crash logs being sent to google that show the navigator object being used before the navigation is setup. I don't know if it's related to this issue. It might be.
