### ISSUE TITLE
Upon setting name and picture for creating BrightID for the 1st time, "create brightid" button is active before setting picture

### ISSUE THREAD

**Issue by alirezapaslar** [BrightID/BrightID#493]
You need to press enter on keyboard to get to the next page where you set the picture. If you don't do that and close the keyboard, you have no option to turn to picture setting page

**Comment by adamstallard** [comment]
The user can press "Create BrightID" before they even have the possibility of uploading a photo (before they have hit return after their name).  This is a confusing flow and shouldn't be possible.
