### ISSUE TITLE
Don't allow a group to be founded with two co-founders that aren't connected. (20-40 Subs)

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#494]
A founder shouldn't be able to select two co-founders that aren't connected to each other.

**Comment by TripleSpeeder** [comment]
@adamstallard Is this still relevant? I think there were some changes done on the backend regarding group eligibility.

**Comment by adamstallard** [comment]
> 
> 
> @adamstallard Is this still relevant? I think there were some changes done on the backend regarding group eligibility.

Not sure, but it hasn't come up in a long time.  If it's a problem, we'll reopen the issue.
