### ISSUE TITLE
Show a users' verification statuses in connection list (20-40 Subs)

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#508]
Right now we show "scores," which people ask and obsess about.  [We should not show scores](https://github.com/BrightID/BrightID/issues/359). What people really want to know is whether their friend is verified. This could be a simple sticker like what we show on the home screen.

The `/users` endpoint returns the `verifications` for each user in the connection list, so we could look at `verifications` for the presence of a certain verification, e.g. "BrightID".

**Comment by TripleSpeeder** [comment]
This is already implemented.
