### ISSUE TITLE
Recovery connection code should be clickable

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#512]
There is no longer a place to paste a code, so generating something like Recovery_{"signingKey":"FFmzdvGxlSW0f3j6s3uGU6Dr4KTP6gZL1k7nc70oSVw=","timestamp":1600132469346}  is useless.

It should create something clickable for the person helping with recovery like https://app.brightid.org/connection-code/L7zrhOU1YFMeMyl0EnPQ%2Fg%3D%3DKjWnjiH5KfPPRLdMag

**Comment by TripleSpeeder** [comment]
This is already implemented.
