### ISSUE TITLE
Show full list of apps in apps tab

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#523]
We want to show all the apps a user can use with BrightID (not just the ones they've linked).  This list can be downloaded from a central server for now.  We'll decide how to curate the list later.

As before, we will continue to show which apps have sponsorships (if a user needs to be sponsored).  Also as before, clicking an app takes a user to the app in their browser.

We also want a visual indication that a user has linked an app (#524) and whether they're verified (and the level) (#525) 

[See also this forum post](https://forum.brightid.org/t/how-users-see-verifications/19).

**Comment by TripleSpeeder** [comment]
This is already implemented.
