### ISSUE TITLE
Different text for sharing link for group connection (5 - 20 Subs)

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#526]
If it's a group connection the link should say

"Make a group connection with X on BrightID: " instead of "Connect with X on BrightID: "

Just so people can tell by the text what kind of link it is.

**Comment by deytulsi18** [comment]
hello, I am getting started with open source, please help me getting stated and solve some beggginer issues.
May I work on this issue ?

**Comment by TripleSpeeder** [comment]
> hello, I am getting started with open source, please help me getting stated and solve some beggginer issues.
> May I work on this issue ?

Happy to welcome you here! All devs hang out in our keybase, please see https://keybase.io/team/brightid to get there. In the meantime you can also check our discord at https://discord.gg/hAxHxb to get started.

**Comment by adamstallard** [comment]
> hello, I am getting started with open source, please help me getting stated and solve some beggginer issues.
> May I work on this issue ?

@deytulsi18 Happy to have your help.  Please reach out to us. :point_up:

**Comment by deytulsi18** [comment]
How do I join the discord, linkit says  expired

**Comment by adamstallard** [comment]
@deytulsi18 https://discord.gg/nTtuB2M

**Comment by deytulsi18** [comment]
Yes I've joined.
Thank you
