### ISSUE TITLE
APK is not available

### ISSUE THREAD

**Issue by xuhcc** [BrightID/BrightID#527]
1. Some time ago the link to APK was added to BrightID website (after some users asked about it in the chat). But now it's gone: https://www.brightid.org/#get-started 
2. The direct link to APK can also be obtained from this issue: https://github.com/BrightID/BrightID/issues/301#issuecomment-611217067. But the modification date of this APK is 11 Aug, so it's not a latest version.
3. When trying to upgrade BrightID on my phone with this APK from Google Drive, the installation fails with `App not installed` error. This could happen if new APK has a different signature, for example when one tries to upgrade "debug" version to production version.
4. A good practice is publishing APKs along with GitHub releases. It's very easy to attach a file to GitHub release and many open-source projects are doing this.

**Comment by RnbWd** [comment]
We are using a different signature for our personal apk versus the play store, so if you've already downloaded the apk from the play store, you will not be able to use our apk. Google took control of our play store signing key and we cannot export it, unfortunately. We had to wait for goggle to approve our app before we could release it on ios or repost our personal apk, that happened a few days ago, so it should probably be updated. We are actually building the apk on every commit now, we just started doing that last month. Thanks for the advice!

**Comment by RnbWd** [comment]
we still need to configure the github action to run on a release or master, right now it's running mostly on dev and side branches

**Comment by xuhcc** [comment]
>We are using a different signature for our personal apk versus the play store, so if you've already downloaded the apk from the play store, you will not be able to use our apk.

I've never used Google Play version. I have version from GDrive installed, dated ~April 2020, but I can't upgrade it to APK currently hosted there because of `App not installed` error.

**Comment by xuhcc** [comment]
OK, so I downloaded the 'release' version from GitHub action artifacts (https://github.com/BrightID/BrightID/actions/runs/264684858) and it installed successfully.

But after start the app shows "Unable to access device keychain, please let BrightID core team know about this issue...". Letting you know :) Though it seems this error only appears on the first launch after the upgrade.

**Comment by RnbWd** [comment]
If you don't see that error message again, then you should be fine. It's
hard to reproduce and only effects android

**Comment by xuhcc** [comment]
Thanks!

The problem has been resolved for me, so we can close this issue. But it would be nice if you add a link to APK back to BrightID website for other users who might need it.

**Comment by adamstallard** [comment]
Now that we have a verified working apk for download, I added it to the [Get Started section of BrightID.org](https://www.brightid.org/#get-started).
