### ISSUE TITLE
Duplicate groups and invite errors after recovery

### ISSUE THREAD

**Issue by RnbWd** [BrightID/BrightID#541]
After social recovery, with a new signing key, the user is unable to decrypt the group data from the invite. After accepting the group invite, the user is prompted to accept the invite again multiple times, which leads to duplicate, unnamed groups saved on the front end.

**Comment by TripleSpeeder** [comment]
With current codebase the invitation is only presented once, so there are no duplicate groups. Still the group name is unknown as it can't be decrypted. 
Created https://github.com/BrightID/BrightID-Node/issues/213 to clear pending invitations on change of signing key.
