### ISSUE TITLE
Unable to access secret key even after reinstalling

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#543]
**Device : Samsung Galaxy E5/ model : SM-E500H**
![Screenshot_2020-09-26-00-40-04-1](https://user-images.githubusercontent.com/205792/94322783-41822d80-ff48-11ea-8c95-791578638476.png)

We shouldn't get in a state where the secret key can't be accessed, but this user reinstalled and it still didn't resolve the problem.

**Comment by TripleSpeeder** [comment]
Duplicate of #510
