### ISSUE TITLE
Connection flagButton does not indicate disabled state

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#545]
When a connection is in waiting state the flagButton (visible after swipe left) is disabled.
The disabled state is not visible for the user, it looks exactly like the enabled state.
The flagBtn should indicate in some way (e.g. greyed out etc.) that it is disabled and has no function.

**Comment by Neozaru** [comment]
What do you think of (`#EBEBE4`) :
![image](https://user-images.githubusercontent.com/1905292/96156969-02754580-0f12-11eb-80aa-69a15fa7a843.png)

Similar color vs. standard disabled fields. White on light gray so not very easy to read, but clear that it is disabled (darker colors still make me feel it's clickable).
Alternative would be to not have swipe-left enabled at all when the connection is in waiting state, but not sure in term of UX. How is this done in iOS-based apps ?
