### ISSUE TITLE
Allow users to view their trusted connections (40-60 Subs)

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#547]
By the way, a "trusted connection" should be renamed to a "recovery connection" to make it more clear what they do.

**Comment by Neozaru** [comment]
I understand that #346 (related issue) is blocked because backend changes are needed.
However, can I start working on this (i.e. just allowing to see Recovery Connections), or do you see an unified component to both view and edit Recovery Connections ?

**Comment by TripleSpeeder** [comment]
I think this issue should be merged with #346 or resolved as duplicate.
@adamstallard Or did you create this issue to have a quick way to just see the trusted connections before we have the full implementation from #346?

**Comment by adamstallard** [comment]
> I think this issue should be merged with #346 or resolved as duplicate.
> @adamstallard Or did you create this issue to have a quick way to just see the trusted connections before we have the full implementation from #346?

@TripleSpeeder Let's keep this open since implementing viewing your recovery connections (preferred name) might be accomplished separately from implementing changing your recovery connections.

**Comment by adamstallard** [comment]
> I understand that #346 (related issue) is blocked because backend changes are needed.
> However, can I start working on this (i.e. just allowing to see Recovery Connections), or do you see an unified component to both view and edit Recovery Connections ?

@Neozaru Yes, you can start working on this, because your recovery connections (as well as the recovery connections for all your connections!) are returned in the user object under the `trusted` element.

**Comment by RnbWd** [comment]
I'll keep this open because we don't have a dedicated screen yet, but this is viewable now

**Comment by TripleSpeeder** [comment]
I think the current solution (showing connection level in the connection list and enable filtering by connection level) is fine.
