### ISSUE TITLE
Enable connection rating

### ISSUE THREAD

**Issue by RnbWd** [BrightID/BrightID#554]
we should have a slider that allows users to rate someone as being close friend / family / acquaintance / or unknown

**Comment by TripleSpeeder** [comment]
Also see discussion at https://forum.brightid.org/t/connection-confidence-levels/12

**Comment by TripleSpeeder** [comment]
Some time ago i threw together a slider prototype using react-native-community-slider:
https://gist.github.com/TripleSpeeder/51fc797834fc4939b0fbe3365366de5d
