### ISSUE TITLE
Allow user to bypass the password and recover without names and photos

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#578]
We shouldn't require a password for recovery of the BrightID--it's only really needed to decrypt the names and photos.

**Comment by Ahmeddh** [comment]
I don't remember my recovery password and now I cant log in even though my 3 social recover have scanned the code and confirmed me!

Is this issue going to be fixed soon or should I create a new bright (if that is even possible)?!

**Comment by TripleSpeeder** [comment]
Providing a password to restore backup is now an optional step in the recovery flow.
