### ISSUE TITLE
"Reconnect with?" screen show old name/photo next to new name/photo

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#582]
To avoid an impersonation attack where someone pushes a new profile to you that impersonates someone you know--hoping that you will give them a high confidence level, we can show the old picture and the old name next to the new picture and name, so you can see the changes you're accepting.

**Comment by adamstallard** [comment]
The buttons could be "accept" or "reject".  If the profile name and photo hasn't changed, we could just update the timestamp without showing any confirmation page, but I'm not sure how easy it is to detect a changed photo.

**Comment by TripleSpeeder** [comment]
Details on the attack we want to prevent:
1. attacker creates a "just met" connection with me in connection party
1. attacker changes his profile to be name and photo of a person I know and trust
1. attacker joins another connection party with me, so i see the name and image of the person i trust and give a high connection level

**Comment by Neozaru** [comment]
> The buttons could be "accept" or "reject". If the profile name and photo hasn't changed, we could just update the timestamp without showing any confirmation page, but I'm not sure how easy it is to detect a changed photo.

But wouldn't we in the real world be able to switch from `Jet met` to `I know and trust` ? For example someone you met during a BrightID party, then getting to know this person more and wanting to upgrade your trust.

In that case, are "accept"/"reject" enough ?
Also being able to see the rating of the connection in the "already connected" case can help prevent the attack because the user will wonder why this known connection as a "just met" rating.

An idea for UX, in the case of someone already connected :
- Remove the "(already connected)" (keep the user creation date)
- Replace the three rating choices by something like "You are already connected with <this trust level>" along with two buttons "Keep"/"Ok" (call to action) or "Change" (smaller). When clicking on "Change", display the three rating choices as for new connections.
That creates friction to change a connection rating, so maybe mitigates attacks while still allowing to change a connection rating.

**Comment by adamstallard** [comment]
> But wouldn't we in the real world be able to switch from `Just met` to `I know and trust` ? For example someone you met during a BrightID party, then getting to know this person more and wanting to upgrade your trust.

Yes, you can update the confidence level of a connection from the connection list without needing to reconnect with someone.

When you reconnect with someone it's just an opportunity to update their profile or the timestamp of the connection. They may have updated their name, photo, or other personal info that they want to share with you.  Since they could also be trying to impersonate someone, you need to be able to reject that update.

**Comment by adamstallard** [comment]
>Also being able to see the rating of the connection in the "already connected" case can help prevent the attack because the user will wonder why this known connection as a "just met" rating.

This is a good idea @Neozaru .  @TripleSpeeder could we also show the confidence level you previously set please on the Reconnect screen?

**Comment by TripleSpeeder** [comment]
current spec from keybase discussion:

**Reconnect screen should display the following information:**
 * old and new photo
 * old and new name
 * old connection level

**The screen should allow these actions:**
 * "Report abuse"
Intended for the "impersonating" attack described above. The connection level will be set as "spam".
 * "Update connection"
Accept the updated profile pic and name. Does not change the connection level.

**Comment by abramsymons** [comment]
> **Reconnect screen should display the following information:**
> 
> * old and new photo
> * old and new name
> * old connection level

I assume that we will not show old and new photo/name if name and photo is unchanged. (I mean the new photo is exactly the same and binary-matching the old one)
I'm not sure when there is no change, what do we want to show user? There will not be any need to "Update connection" and "Report abuse" buttons, yes? We can show a single name/photo (and other info) with a message indicating you were connected before and "Ok" button?
One approach may be skipping such cards in group connections, but I think showing a card with `Ok` button is more general, simpler and better approach.

**Comment by TripleSpeeder** [comment]
> One approach may be skipping such cards in group connections, but I think showing a card with `Ok` button is more general, simpler and better approach.

i like that approach. Should we still submit a "Connect" operation to the server or do nothing?
