### ISSUE TITLE
Use specified font on Android

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#585]
It looks like on Android the app never uses the specified font familiy "Poppins".

I did some tests to find out the problem. I got the correct fonts displayed on Android emulator by doing the following changes:
 - Fonts in folder `assets/fonts` have to be available in **.ttf** format. The *.otf does not seem to work. (Font is available to Download as ttf at https://fonts.google.com/specimen/Poppins)
 - Run `npx react-native link` after copying the .ttf fonts
 - In the styles specify the font exactly like the filename, e.g. `Poppins-Regular` instead of just `Poppins`
 - In the styles, always use the attribute `fontWeight: 'normal'`. If you want to have bold font, change `fontFamily` to `Poppins-Bold`, but keep `fontWeigth: 'normal'`.

I'm pretty sure changing this will break the fonts on iOS, so this topic needs some more research/testing.

Before - After:
![image](https://user-images.githubusercontent.com/754478/97094322-67d4df00-1654-11eb-9c18-9570f1abab4a.png)

**Comment by RnbWd** [comment]
They both look like Poppins to me, the only difference I see is the boldness level. Ttf was the format of the original font by Google, but it wasn't working on iOS. It's possible that the default font on android is almost identical to Poppins. 

The fonts made by damavara on figma use fontWeight: '500', there's only couple places where we are actually using the bold font. I think '500' is actually PoppinsMedium

**Comment by RnbWd** [comment]
Oh wow they are subtly different, the default font on android looks much more similar to Poppins than iOS.

**Comment by RnbWd** [comment]
using exact named fonts will not break ios

**Comment by RnbWd** [comment]
font is fixed now
