### ISSUE TITLE
Update tasks

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#588]
The existing Tasks & achievements do not match reality anymore. Updated list as suggested my @abramsymons on keybase:
- Create your BrightID
- Add a picture
- Make your first connection
- Show up in a call (be checked if user has `SeedConnected` in verifications)
- Link an app
- Show up in a call with a friend/family (be checked if user has `SeedConnectedWithFriend` in verifications)
- Make a few friend/family connections (be checked if user has `Yekta 1` in verifications)
- Setup trusted connections

**Comment by alirezapaslar** [comment]
I think creating brightid is adding a picture and a name. it shouldn't be different. and also by the time they see this list, users have already done both.

Here's what I would do as an achievement list:

Join a verification party and make connections (to be checked if user has seedconnected in verifications)
Get verified on BrightID
Register for an app
Join a close family/friend connection party (or make connections to family and friends)
Select trusted connections
Add a password
Successfully setup social recovery

**Comment by abramsymons** [comment]
> I think creating brightid is adding a picture and a name. it shouldn't be different. and also by the time they see this list, users have already done both.

I agree with removing "Create your BrightID" and "Add a picture".

But I still think "Make your first connection" is a useful achievement and is nice to be the first.

> Join a verification party and make connections (to be checked if user has seedconnected in verifications)
> Get verified on BrightID

We do not need `Get Verified on BrightID` here. As discussed before `BrightID` verification will be removed soon and different apps will require different verifications. "connection party" is also a better name than "verification party".

> Join a close family/friend connection party (or make connections to family and friends)

The achievement I described as "Show up in a call with a friend/family" is what @castall requested and described [here](https://forum.brightid.org/t/level-1-show-up-level-2-bring-friends/24/10). We can call it "Join a connection party with a friend/family". We also need another achievement for "make connections to few families and friends"

> Select trusted connections
> Add a password
> Successfully setup social recovery

They can all be have one achievement called "Setup social recovery".
I suggest this updated list based on @alirezapaslar suggestion:

- Make your first connection
- Join a connection party
- Register for an app
- Join a connection party with a friend/family
- Make connections to few families or friends
- Setup social recovery

**Comment by TripleSpeeder** [comment]
> Join a connection party with a friend/family
> Make connections to few families or friends

@abramsymons Is there already a way to detect this?

**Comment by adamstallard** [comment]
Here are the achievements I am thinking of after recent developments

- Set name and photo (or create profile, or create BrightID) ✔️
- Make a connection ✔️
- Link an app ✔️
- **Get sponsored by an app**
- **Get verified for an app (this includes linking)**
- Make 2 connections ✔️
- Make 3 connections
- Set up social recovery ✔️ (better to call it social recovery or recovery connections)
- **Get verified for 3 apps, 5 apps, 10 apps, etc.** (includes linking)
- **Add more info to your profile**

The bold ones are new.

Notice that verification parties (including ones that you might bring your family to) are not on the list.  I'm on the fence about this.  We might want to send people there, though there are other ways to get verified.  It's probably ok to have some optional achievements like this and "add more info to your profile."  I don't think it's going to hurt anyone to do those things.

I would remove these
- Create a group.  (Most people don't need to do this anymore).
- Get verified. (In favor of getting verified for apps).
