### ISSUE TITLE
Connections on client appear as "deleted"

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#590]
Reported by monomesa in keybase:
> 90% of the connections I just did 20 minutes ago are marked as deleted.
![905ed4ed-6e0c-4d34-b511-5125b1088893](https://user-images.githubusercontent.com/754478/97329749-b1514400-1877-11eb-875e-c21522ecd9bd.jpg)

One affected connection is XttiMvcYfnSpe-Z85zKmJcpttcVeCfFb2M4zxH_lnwQ. It is shown as "deleted" in the app, but on the node api included in the response: 
http://node.brightid.org/brightid/v5/users/OeNllgD2Q2K845Z_ANwah_9yTbJ5PFpvyY8zITkOuFs

@abramsymons already checked that the problem is not related to flagged connections.

**Comment by TripleSpeeder** [comment]
It looks like there are 2 problems involved:
#### If a connection is marked 'deleted' on the client, it can never change back to `verified`
This is a bug in the connections reducer: https://github.com/BrightID/BrightID/blob/49f0c85e7d8b6eddb57e15b6e7941679742795b3/BrightID/src/reducer/connections.js#L49-L56
It ignores any connection update if the local connection state is 'deleted'.

#### We dispatch `fetchUserInfo()` whenever an operation is successfully applied
In the case of group connection it can happen that many operations get applied within a short timeframe. We poll for pending operations every 5 seconds, but the deciding factor is the number of operations included in a block of IDChain. If a block contains 20 operations we are waiting for, they will  appear all in one poll cycle. The client will issue 20 async `fetchUserInfo()` requests in parallel, resulting in responses coming in slow and unordered. This can lead to situations where a "old" response with less entries in connections array comes in **after** a newer response with more connections. Result: existing connections will be marked `deleted`.

This should be fixed in a way that we only dispatch `fetchUserInfo()` once per poll cycle. (And the same for the checkTasks() action!)

**Comment by RnbWd** [comment]
this is interesting, I thought that we over-wrote connections with a `deleted` status, we need to do that
