### ISSUE TITLE
Enable users to filter connections list based on confidence levels

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#595]
Users should only see `already known` and `recovery` connections by default in their connections list.
But there should be some way to see `just met` or `reported` connections to enable users updating levels for those connections.

**Comment by abramsymons** [comment]
We discussed before that we need to enable users see their `recovery` connections. (I think using the `trusted for recovery` term for this level better match the name of other levels)

This can be implemented as part of filtering feature that we are discussing about here.

**Comment by abramsymons** [comment]
We should have such options in the filtering screen.

- Trusted for recovery
- Already known + Trusted for recovery (deault)
- Just met
- Reported

By default users should see connections with both of `already known` and `recovery` levels.

**Comment by adamstallard** [comment]
> 
> 
> We should have such options in the filtering screen.
> 
>     * Trusted for recovery
> 
>     * Already known + Trusted for recovery (deault)
> 
>     * Just met
> 
>     * Reported
> 
> 
> By default users should see connections with both of `already known` and `recovery` levels.

In the connection confirmation screen, we have three levels:

* suspicious
* just met
* already know

If someone marks a user as "suspicious." We should find a way to follow up to get a "reason." This could be done through a notification.

I think a user should also be able to include "suspicious" in the list (like "just met") if it is excluded by default.

**Comment by TripleSpeeder** [comment]
Connection list filtering based on connection level is already implemented.
