### ISSUE TITLE
Downloading connection data taking too long

### ISSUE THREAD

**Issue by alirezapaslar** [BrightID/BrightID#598]
Users from certain regions of the world with slow internet connections have a hard time downloading connection data. Considering the small amount of data, maybe there's a bug somewhere in the process.
Even 1to1 connections sometimes take too long.

**Comment by RnbWd** [comment]
it's pretty slow here in indonesia, it's probably because there's only one, small server running everything, and we don't have a globally distributed cloud of servers

**Comment by adamstallard** [comment]
Yes, the best solution is going to be run more nodes (we're trying to help more people run nodes), and then add some functionality to the mobile app to choose the best node to connect to.  https://github.com/BrightID/BrightID/issues/191 is about that.

If we have 100 nodes running around the world, latency should be much better.

**Comment by TripleSpeeder** [comment]
Closing this as there is no specific bug involved. Once we have more nodes running the situation should improve.
