### ISSUE TITLE
First signature lost from state when recovering

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#676]
When someone is recovering and has a recovery QR code for scanning or a copied link for pasting they might

1. Have the first recovery connection scan (or click) it.
    * it shows an alert `'One of your trusted connections signed your request'`
2. Have the second recovery scan (or click) it.
    * it shows an alert `'One of your trusted connections signed your request'`

The user is stuck on the recovery code screen and never gets to the next screen (restore). The `Set Signing Key` operation is never sent.

For this to happen means the first signature is being lost from redux.  Please make it persist so people can recover their BrightID and not have to make a new one!

Here is the relevant code
https://github.com/BrightID/BrightID/blob/master/BrightID/src/components/Recovery/helpers/index.js#L182-L193

Note this doesn't happen to everyone.  @abramsymons suggested it might be related to leaving the code scanning screen in between scans.  It's also an old bug; Serge noticed it over a month ago.

**Comment by adamstallard** [comment]
@RnbWd This change you made 11 months ago is the source of the problem:
https://github.com/BrightID/BrightID/blame/master/BrightID/src/components/Recovery/helpers/index.js#L130-L131

**Comment by RnbWd** [comment]
I'm not sure if we can safely remove those lines, I think the logic is necessary to reset the state if there's a wrong signature, but I'm not entirely sure. I will look at this line of code in the updated recovery branch

**Comment by adamstallard** [comment]
> 
> 
> I'm not sure if we can safely remove those lines, I think the logic is necessary to reset the state if there's a wrong signature, but I'm not entirely sure. I will look at this line of code in the updated recovery branch

If there's a way to do it that doesn't require the user to stay on that screen (which is tricky and not explained anywhere) that would be ideal.

**Comment by RnbWd** [comment]
this issue should be fixed now
