### ISSUE TITLE
Enable users to see recovery connections of their friends in the profile screen

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#691]
If we enable users to see recovery connections of their friends in the profile screen, if their friend forget who they set as recovery connection, they can help them finding it out.

**Comment by adamstallard** [comment]
Can this be used as an attack?  If I know someone's recovery connections, I can social engineer them into clicking on the code I create for a new account and take over someone's account.

If someone can't remember who they picked as their recovery connection, they didn't do a good job with their selection.  They probably picked people this just met (which isn't actually allowed)

**Comment by adamstallard** [comment]
>  see recovery connections of their friends in the profile screen, 

If this is easy to do fine, but this can be accomplished right now by using https://explorer.brightid.org

**Comment by abramsymons** [comment]
based on my experience with my friends, this feature is the most helpful thing that they need when they want to recover.
I was asked this lots of times from my friends who want to recover that: "who is my recovery connection?"
I agree that if they selected recovery connections more carefully they did not forget that, but it does not mean that we should not help them by simplifying finding the answer.
It's possible to use explorer to find the answer, but if it's important feature and will be used by lots of users, the best place is mobile client.

**Comment by abramsymons** [comment]
This is implemented and can be merged when @RnbWd or @TripleSpeeder had a chance to review it.
https://github.com/BrightID/BrightID/pull/880

**Comment by abramsymons** [comment]
This feature is released now.
