### ISSUE TITLE
Show how long before a recovery connection can be used if it's in the waiting period

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#697]
Users should be able to tell which recovery connections are still in the waiting period.  It could be a different color or symbol.  It should also show somewhere how much time is left.

**Comment by TripleSpeeder** [comment]
I think it is not possible to reliable calculate remaining cooldown period on the client. This would require keeping a history of connection level changes on the client for each connection.

I think cooldown information should be calculated on the backend where all information is available. @abramsymons What do you think?

**Comment by adamstallard** [comment]
> I think cooldown information should be calculated on the backend where all information is available. @abramsymons What do you think?

The cooldown information has to be calculated on the backend. It's only there to protect against attacks. Attackers can easily bypass the client, so the protections have to be on the backend.

As far as calculating on the client whether the backend-enforced cooldown period is in effect, we can have a new variable called `madeFirstRecoveryConnection`.  If they create a new BrightID, it would be set to `false`; if they recover, it would be set to `true`.  If they make a recovery connection, another variable called `timeOfFirstRecoveryConnection` could be set to `now()`, and that variable could be included in the check for whether or not there is a cooldown period in effect.

**Comment by abramsymons** [comment]
Querying recovery connections of a BrightID with its cooldown info is implemented on v6 and also clients are showing cooldown information that is calculated on the server side on recovery connections list of users themselves and their connections.
