### ISSUE TITLE
Show alerts related to cooling period for recovery connection changes

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#701]
We can show alerts

1. Right after recovery change (added or removed)
@RnbWd said
> I think we should just do an alert that says they will not be able to recovery with this person for 1 week

If a recovery connection is being removed we should alert that it can still be used for recovery for a week.

2.  A day before the week is up.  This gives them time to choose new recovery connections if needed, or change their mind about a recovery connection they added accidentally.

**Comment by adamstallard** [comment]
related to https://github.com/BrightID/BrightID/issues/697 "Show how long before a recovery connection can be used if it's in the waiting period"

**Comment by RnbWd** [comment]
we should also have a UI message somewhere on the connection screen and or connection card that indicates that the recovery status is 'pending' or 'will be active in x amount of days'

**Comment by TripleSpeeder** [comment]
> we should also have a UI message somewhere on the connection screen and or connection card that indicates that the recovery status is 'pending' or 'will be active in x amount of days'

This is tracked in #697

**Comment by TripleSpeeder** [comment]
> We can show alerts a day before the week is up.  This gives them time to choose new recovery connections if needed, or change their mind about a recovery connection they added accidentally.

Splitted to https://github.com/BrightID/BrightID/issues/749

**Comment by TripleSpeeder** [comment]
This was implemented and part of release 4.5.0
