### ISSUE TITLE
Enable users sharing their connections/groups info

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#713]
Clients should enable users sharing their connections/groups names/photos with others for different purposes including:

- Helping their friends used social recovery without having backup by sharing mutual connections/groups info with them
- Getting offline backup instead of relying on online BrightID backup server
- Syncing different clients they are using their BrightID with
- Using apps like explorer

The requester user/client/app can create a QR code and the user who wants to share the data can scan that.
The requester creates the channel on profile service, push the request with required signatures to the channel, and share that channel address as a QR code or link with the user who wants to share the data. If scanner confirmed the request, the required data will be encrypted using an AES provided by requester in the QR code and uploaded to channel.

Getting offline backup can be implemented as an client side only app just like explorer which generates a QR code and users can scan that to share their info with the app and download that to their computer.

**Comment by TripleSpeeder** [comment]
> Clients should enable users sharing their connections/groups names/photos with others for different purposes including:
> 
> * Helping their friends used social recovery without having backup by sharing mutual connections/groups info with them

This is implemented

> * Getting offline backup instead of relying on online BrightID backup server
> * Syncing different clients they are using their BrightID with
> * Using apps like explorer
> 
> The requester user/client/app can create a QR code and the user who wants to share the data can scan that.
> The requester creates the channel on profile service, push the request with required signatures to the channel, and share that channel address as a QR code or link with the user who wants to share the data. If scanner confirmed the request, the required data will be encrypted using an AES provided by requester in the QR code and uploaded to channel.
> 
> Getting offline backup can be implemented as an client side only app just like explorer which generates a QR code and users can scan that to share their info with the app and download that to their computer.

These are great ideas, but need more thought and breakup into individual tasks. I think we should close this issue and discuss above ideas in our forum until it is more clear where this is headed.
