### ISSUE TITLE
Some users are not navigated from RecoveryCodeScreen to RestoreScreen

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#738]
@castall shared this screenshot from a recovering user that his qr code scanned by 3 users and was not navigated to next screen yet.

<img src="https://user-images.githubusercontent.com/36688816/106052681-1890c580-60ff-11eb-8c6a-477b6049338c.png" width=300>

**Comment by abramsymons** [comment]
I'm not familiar with react native and I may be wrong but it seems the root of issue is bad use of `useEffect` here:
https://github.com/BrightID/BrightID/blob/master/BrightID/src/components/Recovery/RecoveryCodeScreen.js#L73-L88

```
useEffect(() => {
    const sigs = Object.values(recoveryData.sigs);

    if (!alreadyNotified && sigs.length === 1) {
      // alert user that one of their sigs exists
      Alert.alert(t('common.alert.info'), t('common.alert.text.trustedSigned'));
      setAlreadyNotified(true);
    } else if (sigs.length > 1) {
      // stop polling channel if 2 sigs exist
      // navigate after one cycle
      setTimeout(() => {
        clearChannel();
        navigation.navigate('Restore');
      }, CHANNEL_POLL_INTERVAL);
    }
  }, [recoveryData.sigs, alreadyNotified, t, navigation]);```
  
I guess this code is not triggered when `recoveryData.sigs` is updated because it's an array and array does not change when new item is added to.
https://stackoverflow.com/questions/59467758/passing-array-to-useeffect-dependency-list

So how does it work for some users? Maybe that code was triggered when they switched screen? I'm not sure!

**Comment by TripleSpeeder** [comment]
> I guess this code is not triggered when `recoveryData.sigs` is updated because it's an array and array does not change when new item is added to.

After looking in detail at the code i don't think this is the problem. The reducer is implemented with createSlice from RTK, which internally uses the `immer` library to manage immutable state. So any change like adding a new signature will result in a new `sigs` object. There is no codepath that would just add childs to the existing object. So the dependency should be fine.

**Comment by RnbWd** [comment]
I found a solution and already merged it into DEV, I will keep this issue open in case we see it again, but it was the timeout inside of the effect not firing, preventing navigation. See this commit: https://github.com/BrightID/BrightID/pull/742/commits/ba9f0b575543f7404b0f9851f85a731f93229a9c
