### ISSUE TITLE
Some users get "Bad QR Data" when they scan recovery qr code

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#739]
@castall reported some users are getting "Bad QR Data" randomly when they scan recovery qr code to help their friends recovering their accounts.

**Comment by abramsymons** [comment]
The error seems to be raised from [here](https://github.com/BrightID/BrightID/blob/0ff737b10708da41d7408cbb7d1e20f794ead194/BrightID/src/components/Recovery/thunks/channelDownloadThunks.js#L26). The reason seems to be the channel expired and there is no `data` dataId to download.
I'm curious how this can happen.
I reviewed how channel `expire` time is used to re-upload the `data` but I guess it may has problems.
If the channel is not expired yet and it will in few seconds, current approach seems to fail uploading `data` and it waits another 15 minutes to upload again.
I think instead of relying on `expire` time, we should get list of channel dataIds every time we poll the channel and if `data` is not there, upload it again.
In fact, I'm suggesting to update this section of [`checkChannel`](https://github.com/BrightID/BrightID/blob/master/BrightID/src/components/Recovery/thunks/channelThunks.js#L89) function:
```
  if (expires && Date.now() - expires > 0) {
    // create new channel if date is expired
    console.log(`channel expired, creating new channel`);
    await dispatch(createChannel());
    return;
  }

  const channelApi = new ChannelAPI(url);
  const dataIds = await channelApi.list(channelId);
```
to be changed to something like this:
```
  const channelApi = new ChannelAPI(url);
  const dataIds = await channelApi.list(channelId);
  if (!dataIds.includes('data')) {
    // create new channel if it is expired
    console.log(`channel expired, creating new channel`);
    await dispatch(createChannel());
    return;
  }```

**Comment by TripleSpeeder** [comment]
IMO The best solution would be to prevent the channel from expiring at all by re-uploading own data shortyl before expiry. When https://github.com/BrightID/BrightID-Node/pull/192 is merged, the profile server will take reupload of existing data as a signal to reset the channel TTL.
