### ISSUE TITLE
Impossible to recover account although within cooldown period

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#762]
**Scenario:**
Alice has set Bob as recovery connection. Bob has Alice connected as "just met":
Connection Alice->Bob is "recovery", Bob->Alice is "just met"

1. Alice changes connection level of Bob to "just met":
Connection Alice->Bob is "just met", Bob->Alice is "just met"

2. Alice needs to recover:
Bob should still be able to recover Alice, because Alice had him set as "recovery" shortly before (within 7 days cooldown period).
Bob scans Alices code, opens TrustedConnectionsScreen.

**Expected behaviour:**
Although the current connection Alice -> Bob is "just met", Bob should still be able to recover Alice, because he was recovery level before and the cooldown period is not yet expired.

**Observed behaviour:**
Bob can not select Alice to recover. 

This happens because the list of recovery candidates is built based on the current connection level, but not on the history:
```typescript
api.getConnections(id, 'inbound').then((connections) => {
        const recoveryIds = connections
          .filter((conn) => conn.level === 'recovery')
...
```

**Comment by adamstallard** [comment]
If I'm understanding this correctly, the cooldown period for not being able to remove a trusted connection doesn't work.  Is this correct @abramsymons ?

So if an attacker gains access to my BrightID and sets my recovery connections to "just met" or "suspicious" then I have no way to override this and regain control of my BrightID.  In other words, the cooldown period just doesn't work.

Is this a frontend problem only, or is it also with the backend?

**Comment by TripleSpeeder** [comment]
After scanning a recovery code you need to select the connection that you want to recover. Currently the frontend does not offer all existing connections, but only the connections that right now have set me as "recovery".
With the cooldown mechanism the frontend does not know which connections can be recovered.

The quick fix is to just show all connections in the frontend instead of only the ones of level "recovery". The downside is that the user may need to search a while to find the connection he wants to recover. But this is better than not being able to recover at all.

A further improvement would be to have a new API method that returns all connections that I am currently able to recover. @abramsymons what do you think?
