### ISSUE TITLE
Can't find connection on invite to group list

### ISSUE THREAD

**Issue by CurlyBracketEffect** [BrightID/BrightID#770]
I am using v4.5.0 on a Google Pixel running Android 11 

I recently onboarded a group of friends to BrightID. I first did a group connection so that all of us would be connected directly to each other. I then went on to create a Group in the app for us all to join. I selected 2 of them at random to be the Group admins along with me and created the group. I then went through my list to add all the other people to the Group. Everyone appeared on my list except for one person. I have scrolled through the list several times, but I can't find them on the "invite list". I can see him when I back out and go to my full connections list. This person is one of my Recovery connections as well. I asked the other admins if they can find him on their list and add him to the group, but neither of them can find him as well. 

I have tried closing the app and restarting it. 
It would appear I am on the most current version. 
When I search for him in my connections I can see that he has enough mutual connection in order to qualify to be added to the group. He is connected to every other person that is currently in the group. 
The group currently has 9 people in it and I am planning on adding more friends soon.

Not sure what else I could try, but considering the other admins can't see him on the invite list either I feel like this is some sort of bug.

(I will add that I have several connections on my list as a "BrightId Star" so it is painful to have to scroll through all my connections every time I want to try and add them, but I see that there is already an issue open for this here: #628 )

**Comment by RnbWd** [comment]
Thank you for reporting this and being a BrightId Star! I'll copy this message to our keybase channel and see if we can figure out the issue. It's been reported before, so I know it's not unique to this latest release. I'll ask to see if anyone has solved this issue in the past.

**Comment by TripleSpeeder** [comment]
I believe this should be fixed with commit 591d56a5fbf88cb78d38ca0aa882d56c56be01d3 which has been released. Closing.

**Comment by RnbWd** [comment]
Hopefully the changes that we released yesterday fix this issue for you!
