### ISSUE TITLE
UI mockups for mobile app

### ISSUE THREAD

**Issue by stuk88** [BrightID/BrightID#8]
We should create a wireframe mockup of the app using Axure, or InvisionApp, or just a simple Google Drive Sliders.

If we'll have a UI mockup in invisionApp, we could get reviews on that from users before we actually build it.

**Comment by adamstallard** [comment]
https://github.com/Brightside-Social/brightside/issues/2

**Comment by adamstallard** [comment]
@NickXML created one set of google slides and is working on another.  I think any of us that are designer types should just make mockups to share with each other.  Even just one screen (not a full UI) is useful to start talking about it.  Let's not worry about stepping on each other's toes.  

We've had our discussions in https://github.com/Brightside-Social/brightside/issues/2  but it's easier to talk about a picture than about text.

@stuk88 Are you game?

**Comment by adamstallard** [comment]
@rstallar are you game?

**Comment by rstallar** [comment]
Definitely. I'm catching up with the discussions and putting something together. I'll try to get up a rough pass once I have it so we can keep the discussion going

**Comment by adamstallard** [comment]
I have a new description of the mobile app https://github.com/BrightID/BrightID/wiki/BrightID-Mobile that shows that our central offering is an ID, and we're requiring groups.

@rstallar @NickXML @stuk88 @Aleksion 

Would you care to make a mockup of one of the screens from that app description and we can talk about it?

Or even just ask me some questions so I can improve the written description.

Thanks!

**Comment by adamstallard** [comment]
If you're interested in figuring out how you can help with BrightID, we're having a kick-off meeting.  Here's the time poll about when it will be: https://www.loomio.org/p/DgPUVIBy/brightid-kickoff-meeting-online-  We've broken down the tasks into smaller chunks, and there will bounties provided by giveth.io who is sponsoring our project.
