### ISSUE TITLE
A warning note about explorer private information

### ISSUE THREAD

**Issue by rightehsan** [BrightID/BrightID#829]
A warning note is needed to be shown to users before they log in to the explorer saying " Your BrightID and your password are crucially confidential. Never share them with anyone and keep them safe" or another statement like this.

**Comment by adamstallard** [comment]
This belongs in the [BrightID Explorer repo](https://github.com/BrightID/BrightID-Explorer).

See also https://github.com/BrightID/BrightID-Explorer/issues/5
