### ISSUE TITLE
Add Trusted Connections to Side Menu 

### ISSUE THREAD

**Issue by RnbWd** [BrightID/BrightID#834]
Currently it is difficult for users to view their trusted connections. We want users to clearly see who their trusted connections are, and edit their trusted connections, from a separate screen that will be accessible from the side menu. 

We already have a screen that allows users to select trusted connections, but that screen is only accessible from a notification, and it is only shown once. We would like to migrate that screen to a new set of screens, styled slightly differently, that display trusted connections, and also allow you to pick new trusted connections, which is similar to the screen showed by the notification.

We would like that screen to be replaced with the following, accessible from the side menu:

![image](https://user-images.githubusercontent.com/5370305/129023281-0a8ffa88-3bd0-4759-89f4-23dcc168f0cc.png)

![image](https://user-images.githubusercontent.com/5370305/129023356-74322a81-97d3-414d-8493-cafcd7c13d68.png)

![image](https://user-images.githubusercontent.com/5370305/129023394-399a0805-8ac3-40ac-8351-f58ec2e19672.png)

![image](https://user-images.githubusercontent.com/5370305/129023404-75fa0f35-d19e-4f87-bab2-dca44e475e87.png)

**Comment by TripleSpeeder** [comment]
This has been implemented.
