### ISSUE TITLE
FairDrop Amount is not showing correctly

### ISSUE THREAD

**Issue by giangnt60014** [BrightID/BrightID#850]
Hi, I believe with my contribution during r9 and contribute directly to BrightId in gitcoin, I should receive more than just 80 $Bright. 
Besides that, when I set up trust bonus in Gitcoin with my BrightID, Gitcoin show Linked, but don't know why the BrightID app did not show Linked with Gitcoin. any other apps show Linked as normal.
My wallet: 0xb0dB0A18Ba8309b66AA54eA5bb55f4f457CA3Ea8
Can someone help me to check my case?
Thanks

**Comment by TripleSpeeder** [comment]
please use our discord for support requests

**Comment by giangnt60014** [comment]
Hi Michael,

In Discord, your team asked me to create a github issue???
