### ISSUE TITLE
I didn't receive fairdrop 

### ISSUE THREAD

**Issue by riplucky** [BrightID/BrightID#851]
Dear Team, 

I used BrightID before  Sep 9, Completed achievements in the BrightID app, verified for 24 apps. I linked Gitcoin with BrightID but the BrightID app didn't show linked sticker. I donated for BrightID in Gitcoin. 

I haven't received the fairdrop

Could you help me to double-check my case. My wallet address 0xc8Cf6B03C2Aa80de2579dF02aA3beD1e716E1680

Thank you for your time.

Regards
Tuan Tran

**Comment by fscwx** [comment]
Mr. I registered and certified in april. And I've been involved in some projects. But why do I  have nothing coins? Doesn't that seem reasonable?My wallet address 0xC1Ff85c123290878D8fa84Bfd123b3c81909Fe22

**Comment by TripleSpeeder** [comment]
please use our discord for support requests
