### ISSUE TITLE
QUALIFIED BUT NOT GIVEN ANY $BRIGHT 

### ISSUE THREAD

**Issue by almaroof** [BrightID/BrightID#857]
![Screenshot_20210919-185231](https://user-images.githubusercontent.com/34830472/133937727-fb81feaf-59d6-4ba6-82db-e07d6a97365e.png)
My wallet is qualified but no $bright allocated

0x1734eD2675cdcEe41848a2Cf3d6022FF0abeE64A

**Comment by TripleSpeeder** [comment]
Please use our discord for support requests.
