### ISSUE TITLE
when i  recovery my brightID ,the APP  warns this mesage 

### ISSUE THREAD

**Issue by dh360** [BrightID/BrightID#859]
![brightid](https://user-images.githubusercontent.com/7079487/134132383-a9f401fc-147b-4b66-a6d9-2764ab7ba525.jpeg)

**Comment by TripleSpeeder** [comment]
This looks like you do not have the correct recovery connections set up. Please go to our discord at https://discord.gg/EK9YNEW and ask in one of the HELP channels.
