### ISSUE TITLE
dao.brightid.org sometimes fails upon return

### ISSUE THREAD

**Issue by nothingtwisted** [BrightID/BrightID#860]
**Suggestion:** explore interaction with Brave Shields for dao.brightid.org to improve UX.

**Context:** After previously successfully interacting with the DAO and wrapping $BRIGHT, returning to the page, later on, yielded a blank white page. Clearing the cache & cookies didn't resolve the issue but disabling Brave's Shields did. Notably, the site continued working when I immediately re-activated Shields. So disabling and (if so inclined) re-enabling Shields resolves the issue. 

**Note:** One of the admins in Discord mentioned that other users have experienced this in Chrome or Safari, so the issue could be unrelated to Brave Shields or there could be multiple inter-related issues.

**Comment by nothingtwisted** [comment]
Sadly, I visited and it's broken again. De-activating and re-activating shields didn't help this time.

**Comment by TripleSpeeder** [comment]
Thank you for this report. Can you access the browser console and attach the output here, if there is any?

**Comment by TripleSpeeder** [comment]
I think 1hive team has improved the gardens website. Closing.
