### ISSUE TITLE
linked some apps problem

### ISSUE THREAD

**Issue by jambestwick** [BrightID/BrightID#862]
![Screenshot_20210922_134119.jpg](https://user-images.githubusercontent.com/18340126/134289191-7fd1ab9a-ff81-4b98-ae74-4da1924f9de3.jpg)

when linked clr.fund ,IDChain linked tag disappear
when linked IDChain,clr.fund linked tag disappear

**Comment by TripleSpeeder** [comment]
There was a similar report in our AMA meeting today. It looked like there is a limit of 5 apps that the UI will show as linked, when linking more apps another app appears unlinked.
