### ISSUE TITLE
Could not join connection channel. Error message: download channelInfo.json

### ISSUE THREAD

**Issue by oliveryunchang** [BrightID/BrightID#869]
When I scan a recovery QR code(Generated by iOS),and we are recovery connections, I get an error message. 
The error message is “Could not join connection channel. Error message: download channelInfo.json from channel null: Unexpected response format”.

I use Android，My friend uses iOS. It OK to see a list  and select someone as the user they are helping to recover when I scan a revocery QR code (Generated by Android) .So I gress **BrightId APP is not compatible with ios and Android**

**Comment by TripleSpeeder** [comment]
iOS and Android apps are compatible in general. Can you check which app version is installed on both devices? If one app version is outdated by major number it will not be compatible. In other words - both versions should be at version 4.x.x.

**Comment by oliveryunchang** [comment]
My app version is 4.3.0(Android), another version is  4.6.5(iOS)

**Comment by jaosnzhang8223** [comment]
Where can I download 4.3.0 App version?
