### ISSUE TITLE
Help users find friends and family having BrightID

### ISSUE THREAD

**Issue by abramsymons** [BrightID/BrightID#938]
BrightID users are already using different platforms with different identifiers. They have for example phone numbers, emails, or accounts in social networks like Twitter, Instagram, Facebook, and... There can be registries that BrightID users can optionally register their current identifiers in to enable their friends to find them simply when they install BrightID.

For example, there can be a registry of phone numbers that the BrightID mobile app can optionally query phone contacts for new users and inform them which of their contacts has BrightID and even enable them to request a connection via SMS. There can be such a registry for emails or different social networks.

Users BrightID should not be linked to users' identifiers in the registries. Registries should only contain a list of identifiers that have BrightID. Registries can not be hosted on blockchains like IDChain because users should be able to remove their ids to comply with PII. Registries are preferred to not be public to prevent spammers use them to spam BrightID users.

BrightID verification will be used to enable every unique user to add a single record to the registry of each platform. This approach will be used instead of ownership verification of identifiers for each platform to make adding multiple identifiers simpler for users. Users can add invalid identifiers following the BrightID verification approach, but such a thing will rarely happen and real owners of identifiers can exclude them from registries by contacting our support.

The server-side apps will be implemented just like other apps that integrate with BrightID to verify users. There should be different apps for different social platforms to prevent linking identifiers of users in them together. To simplify usage for users, unlike other apps that integrate with BrightID, the BrightID mobile client will be the client of the app and there will be no need to scan a QR code and follow a deep link to be able to add records to the registries.

The BrightID mobile client creates a key pair for each social platform registry app and links its public key to the blind sig created for that app to enable the server-side app to query verification to allow users to add a single record to the registry.  Users can also remove their own added identifiers from registries by signing requests with the private part of the key pair.

**Comment by abramsymons** [comment]
@TripleSpeeder suggested:
> Can we use a trapdoor function to only store hashes of the identifiers in the registry? 
> - when adding a phone #, the client submits hash(phone) to the registry.
> - when looking for existing contacts, the client hashes each phone number and checks if the hash exists on the server. If yes, > client knows that the contact with that phone# uses BrightID.

**Comment by adamstallard** [comment]
> @TripleSpeeder suggested the following to improve privacy issues and not make our backend a nice target for hackers.
> 
> > Can we use a trapdoor function to only store hashes of the identifiers in the registry?
> > 
> > * when adding a phone #, the client submits hash(phone) to the registry.
> > * when looking for existing contacts, the client hashes each phone number and checks if the hash exists on the server. If yes, client knows that the contact with that phone# uses BrightID.

Just hashing isn't sufficient.  Each entry will need its own random salt to avoid a rainbow attack which would easily reveal all the phone numbers.

That said, I'm sure spammers already have a list of all viable phone numbers, just like anyone can easily get a list of all viable twitter accounts.

**Comment by adamstallard** [comment]
> BrightID users are already using different platforms with different identifiers. They have for example phone numbers, emails, or accounts in social networks like Twitter, Instagram, Facebook, and... There can be registries that BrightID users can optionally register their current identifiers in to enable their friends to find them simply when they install BrightID.
> 
> For example, there can be a registry of phone numbers that the BrightID mobile app can optionally query phone contacts for new users and inform them which of their contacts has BrightID and even enable them to request a connection via SMS. There can be such a registry for emails or different social networks.
> 
> Users BrightID should not be linked to users' identifiers in the registries. Registries should only contain a list of identifiers that have BrightID. Registries can not be public and should be hosted privately to prevent spammers use them to spam BrightID users. The server app of the registry can verify ownership of phone numbers or users identifiers on other platforms to enable adding or removing new records to the registry.

I agree with the first two paragraphs.

As far as the third paragraph, you had suggested before that we use BrightID to allow one entry in each social identifier registry per person.  Now you seem to be advocating using SMS verification instead.  Let's contrast the two approaches.

In one case, we will need to send an SMS each time the user wants update one of their social accounts, to provide access to our backend, to avoid linking all of a user's accounts together--or they could provide proof of ownership of the social account to our backend (such as sending a custom tweet), which could be equally annoying.

If we use BrightID, we could use BrightID nodes to sign one unique identifier per person per registry (could be a public key of a key pair) which would allow the person to update their encrypted social identifier and limit them to one entry per registry.  This seems like a simpler solution.  It's certainly simpler from an end user's perspective, because it doesn't require any interaction from them--other than to give the BrightID mobile app access to the identifier of their social account or phone number (which we need to do anyway).

**Comment by adamstallard** [comment]
> @TripleSpeeder suggested the following to improve privacy issues and not make our backend a nice target for hackers.
> 
> > Can we use a trapdoor function to only store hashes of the identifiers in the registry?
> > 
> > * when adding a phone #, the client submits hash(phone) to the registry.
> > * when looking for existing contacts, the client hashes each phone number and checks if the hash exists on the server. If yes, client knows that the contact with that phone# uses BrightID.

If the API allows to look up someone by their phone # to see if they're in the registry, I don't know how we stop anyone from finding the complete list by trying millions of phone numbers.

These registries are going to be basically be public and there's nothing we can do about that right?

I think the best we can do is allow people to remove themselves from the registry, but not avoid being publicly listed.

**Comment by abramsymons** [comment]
> I agree with the first two paragraphs.
> As far as the third paragraph, you had suggested before

The description of the issue was updated based on discussions on Keybase.
