### ISSUE TITLE
Old user showing up as brand new

### ISSUE THREAD

**Issue by adamstallard** [BrightID/BrightID#968]
When I connect to people they see this

![image](https://user-images.githubusercontent.com/205792/156649729-2a41c8dc-cb43-4439-bb36-11160abe1709.png)

Has there been a regression for info about a user you're connecting to is no longer shown?  I first noticed this a couple of months ago.  I'm not sure how long this bug has existed, but this feature used to work.

**Comment by TripleSpeeder** [comment]
@adamstallard I can only reproduce this when the person scanning the code does not yet have any connection (=> is a brand new user not yet existing in the node database). Any incoming connection for this type of user appears as "Joined BrightID a few seconds ago".
Does this match your observation? Or are you also seeing this with users already having connections?

**Comment by TripleSpeeder** [comment]
After discussion with @abramsymons this will be solved by next node release (see https://github.com/BrightID/BrightID-Node/commit/1fed0d2a1710e21b0080796665ee83dc67572914)
