### ISSUE TITLE
Set up webrtc data channels

### ISSUE THREAD

**Issue by RnbWd** [BrightID/BrightID#97]
Configure webrtc for building in xcode and android studio
Decide on an implementation for passing info in order to establish the connection
Write the code for passing data between devices

**Comment by RnbWd** [comment]
This is a necessary in order to complete https://github.com/BrightID/BrightID/issues/89

**Comment by RnbWd** [comment]
completed

**Comment by adamstallard** [comment]
Closing in favor of the profile web service.  See https://github.com/BrightID/BrightID/wiki/QR---Websocket-architecture
