### ISSUE TITLE
Account Recovery Operation times out too fast

### ISSUE THREAD

**Issue by TripleSpeeder** [BrightID/BrightID#970]
This was reported via discord user and by @abramsymons.

When starting the recovery process, the "Recover account" part shows the "operation timed out" message after ~20 seconds of waiting. 
This indicates an error somewhere, because the client should wait 2 minutes before assuming an operation has timed out.
![IMG_6715](https://user-images.githubusercontent.com/754478/156739259-14d5198b-d5d5-441a-a02a-931e6872976a.jpeg)

**Comment by TripleSpeeder** [comment]
I did not yet find a way to reproduce this issue.

**Comment by abramsymons** [comment]
fixed in https://github.com/BrightID/BrightID/commit/4085342a5449c3d828bc47fde3a50d4c7ff62da4
