### ISSUE TITLE
Logged out after closing app; reinstalled & the app crashes upon opening

### ISSUE THREAD

**Issue by kenchester** [BrightID/BrightID#995]
Installed BrightID on a Pixel 4a running Android 12 recently. It kept logging me out every time I re-entered the app at first, so I decided to uninstall/reinstall the app. Now, after several attempted reinstalls, it crashes immediately upon launching the app.

**Comment by TripleSpeeder** [comment]
Did the app ever run fine on your device before the problems started?

**Comment by kenchester** [comment]
It did let me use the app & create accounts for my first install, but that
installation had it's own bug which caused me to do the initial uninstall.

On the first installation, every time I closed the BrightID tab or turned
off my phone, I was logged out. This forced me to create numerous BrightID
accounts because there's (rather oddly) no password login – and I had just
created the logged out account, so I had no method to socially
authenticate. Therefore creating a new account was the only way forward.

After having to create several accounts, I figured I could solve the bug
with an uninstall & then it never worked after I reinstalled. It would
always crash immediately.

**Comment by TripleSpeeder** [comment]
Hmm, that is the first time i hear of such a problem :-( I have a Pixel 4a myself and the app is working fine. 
Can you double check the permissions? It should have file/media access and camera. Also possible root cause could be if your phone is running out of storage space. But you probably would get OS-level warnings all the time already...

**Comment by kenchester** [comment]
Hi Michael,

My storage is clocking in at 79.41 GB free.
Granted all app permissions & it still crashed, even with several restarts
of the phone.

Every time I choose to uninstall, I told it to erase app data (attached),
but only after I went into Settings after another reinstall (Settings >
Apps > BrightID > Storage & Cache > Clear Storage) & cleared storage
manually did it work again this morning. The automatic data erasure upon
uninstall simply wasn't sufficient.

Now that I've gotten the app to reopen, my remaining bug is that the login
screen is missing a login button. I created a password when setting up an
account, but for the life of me, the app won't let me use that same
password to log in.

It only says "Create my ID", "recover", and "import" and lacks a login
button where I can enter my username & password (the app only had me create
a password, so I'm actually not sure what my username is...).

Since the app logs me out every time that I close the app window, I think
I've created 6 or 7 BrightID accounts that are useless now because I can't
log in.

**Comment by TripleSpeeder** [comment]
Hey Ken, i think this is a misunderstanding with the app functionality. With BrightID app there is no account based on email and password. The password in the create BrightID flow is optional and used to create an encrypted backup of your connections metadata (names, photos, etc). 

When you open the app and click on "Create My BrightID" you should be asked to set a name and a profile picture, then an optional backup password. Then you should end up in the main menu of the app. Now when you close the app and restart it, are you again at the initial signup screen with the "Create My BrightID" button? This should *not* happen - The app should remember you and immediately start with the main menu. You should not need to enter anything.

**Comment by kenchester** [comment]
Yes, everytime I close the BrightID tab on my phone, let alone restart my
device, I find myself again at the initial signup screen with the "Create
My BrightID" button.

I tried to reproduce what exact issues caused this. When I skipped the
password creation at the beginning today, the app stayed logged in. When I
did a password, but pulled the profile picture from my love camera vs. my
albums, it stayed logged in. So far, I've reproduced this error when
creating a password + pulling the profile pic from my album, but it's
stayed logged in on some of my account creations, so I'm not sure if I've
identified the exact error conditions yet.

**Comment by kenchester** [comment]
Still having this same issue of the app logging me out after closing the
BrightID tab – it returned me to the licence agreement page again today.

Although I'd be losing some cash from the Manna project, I think I'm going
to have to abandon BrightID for now, since it's just too buggy on Android
12 apparently...
