### ISSUE TITLE
Provide smooth upgrade path from older versions

### ISSUE THREAD

**Issue by bitsikka** [BrightID/BrightID#998]
I have family members who rarely use BrightID but have it installed for them to be my recovery connection. I recently asked them to open the mobile app for it to be upgraded to the latest version. Their version is v4.7.7 and latest is v4.13.3.  It would not upgrade automatically, nor if clicked on Menu>Check for Updates.

**Comment by TripleSpeeder** [comment]
There should be an update in Google Play/Apple Appstore for people running 4.7.x version. Can you check if they can update to the latest version via Google Play/Appstore (i think it is 4.8.1)?
When they have the current store build installed, they should get the automatic over-the-air update to the latest 4.13.3 when starting the app.

**Comment by bitsikka** [comment]
I see. I did as you suggested and it worked!

Thanks! @TripleSpeeder 

Closing the issue.
